# DO NOT EDIT. Generated by protoc-gen-pydantic.
"""
These protos have been ported over from the Roubst Intelligence repo. It is mainly from
https://github.com/RobustIntelligence/rime/blob/master/protos/ri/api/generativevalidation/generative_validation_service.proto
but has had other RI protos merged into this one file for simplicity.
NOTE: This is NOT meant to be a permanent solution, will update when we have finalized a plan.
"""
from typing import Any as _Any

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)

from ._proto_types import (
    ProtoInt64,
    ProtoTimestamp,
    ProtoUInt64,
    _EnumValueOptions,
    _ProtoEnum,
)


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class ModelResponseAnalyzer(_ProtoEnum):
    """
    DEPRECATED: Model analyzer choice is no longer supported. The method (or
    model) to use to analyze customer model respones (whether or not an attack
    was successful).
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    GEMMA_3 = ("GEMMA_3", 2)


class AWSRegion(_ProtoEnum):
    """
    AWSRegion are the list of regions available to test in.
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    US_EAST_1 = ("US_EAST_1", 1)
    US_WEST_2 = ("US_WEST_2", 2)
    EU_CENTRAL_1 = ("EU_CENTRAL_1", 3)
    AP_NORTHEAST_1 = ("AP_NORTHEAST_1", 4)


class ExternalApiProvider(_ProtoEnum):
    """
    ExternalApiProvider specifies the external API provider to use for the model connection
    spec.
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    AZURE_OPENAI = ("AZURE_OPENAI", 1)
    OPENAI = ("OPENAI", 2)
    ANTHROPIC = ("ANTHROPIC", 3)
    GEMINI = ("GEMINI", 4)
    MISTRAL = ("MISTRAL", 5)
    CUSTOM = ("CUSTOM", 6)
    LANGGRAPH = ("LANGGRAPH", 7)


class AttackResult(_ProtoEnum):
    """
    AttackResult is the result of an attack example on the model
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    # That attack was successful. I.e., the model was vulnerable to the attack.
    SUCCEEDED = ("SUCCEEDED", 1)
    # The attack failed. I.e., the model was not vulnerable to the attack.
    FAILED = ("FAILED", 2)
    # An error was encountered when trying to run the attack.
    ERROR = ("ERROR", 3)


class Industry(_ProtoEnum):
    """
    Industry vertical used to bias red team attack generation.
    UNSPECIFIED falls back to INDUSTRY_DEFAULT inside the data plane.
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    DEFAULT = ("DEFAULT", 1)
    HEALTHCARE = ("HEALTHCARE", 2)
    FINANCIAL_SERVICES = ("FINANCIAL_SERVICES", 3)
    TECHNOLOGY = ("TECHNOLOGY", 4)
    RETAIL = ("RETAIL", 5)
    EDUCATION = ("EDUCATION", 6)
    GOVERNMENT = ("GOVERNMENT", 7)
    MANUFACTURING = ("MANUFACTURING", 8)
    ENERGY = ("ENERGY", 9)
    EQUIPMENT_RENTAL = ("EQUIPMENT_RENTAL", 10)
    HUMAN_CAPITAL_MANAGEMENT = ("HUMAN_CAPITAL_MANAGEMENT", 11)


class Severity(_ProtoEnum):
    """
    Severity specifies the security risk level of a generative test.
    """

    # protolint:disable:next ENUM_FIELD_NAMES_ZERO_VALUE_END_WITH

    # buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
    # SEVERITY_NONE is semantically meaningful (no risk), not "unspecified".
    NONE = ("NONE", 0)
    # Indicates low risk.
    LOW = ("LOW", 1)
    # Indicates medium risk.
    MEDIUM = ("MEDIUM", 2)
    # Indicates high risk.
    HIGH = ("HIGH", 3)
    # Indicates critical risk.
    CRITICAL = ("CRITICAL", 4)
    # Indicates this field was not set. Attack not run, result invalid.
    NOT_SET = ("NOT_SET", 5)


class AttackType(_ProtoEnum):
    """
    AttackType specifies the type of attack to run against the model.
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    SINGLE_TURN = ("SINGLE_TURN", 1)
    MULTI_TURN = ("MULTI_TURN", 2)
    CUSTOM_GOAL = ("CUSTOM_GOAL", 3)


class AttackModality(_ProtoEnum):
    """
    AttackModality specifies the type of content contained within the attack run
    against the model.
    """

    UNSPECIFIED = ("UNSPECIFIED", 0)
    TEXT = ("TEXT", 1)
    IMAGE = ("IMAGE", 2)
    AUDIO = ("AUDIO", 3)


class WebsocketResponseTypeConfig(_ProtoEnum):
    """
    WebsocketResponseTypeConfig specifies how the websocket server sends responses.
    This is optional - if unspecified, behavior depends on response_json_path:
    - If response_json_path is empty: streaming text mode (accumulate all messages)
    - If response_json_path is set: single message mode (read and parse one message)
    """

    # Unspecified: behavior determined by response_json_path (see enum description).
    UNSPECIFIED = ("UNSPECIFIED", 0)
    # Single JSON response with log skipping: Server may send multiple messages including
    # logs (JSON or text). Non-JSON messages are ignored. Returns the first JSON message
    # that contains the response_json_path.
    SINGLE_JSON = ("SINGLE_JSON", 1)


class PromptBank(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    # v1 prompt banks are deprecated. Use the v2 prompt banks instead.
    DEFAULT = (
        "DEFAULT",
        1,
        _EnumValueOptions(deprecated=True),
    )
    QUICK_SCAN = (
        "QUICK_SCAN",
        2,
        _EnumValueOptions(deprecated=True),
    )
    DEMO_SCAN = (
        "DEMO_SCAN",
        3,
        _EnumValueOptions(deprecated=True),
    )
    MAX = (
        "MAX",
        4,
        _EnumValueOptions(deprecated=True),
    )
    DEFAULT_V2 = ("DEFAULT_V2", 5)
    QUICK_SCAN_V2 = ("QUICK_SCAN_V2", 6)
    CUSTOM_GOALS = (
        "CUSTOM_GOALS",
        7,
        _EnumValueOptions(
            value_visibility=None,
        ),
    )
    # Lite, single-turn-only variant of the quick scan prompt bank (curated,
    # reduced set of attacks).
    QUICK_SCAN_LITE_V2 = (
        "QUICK_SCAN_LITE_V2",
        8,
        _EnumValueOptions(
            value_visibility=None,
        ),
    )


class Language(_ProtoEnum):
    """
    We use EN as the default value because prior to 2.10 we didn't
    have a language option for generative testing, and we implicitly
    assumed English was the language.
    By making EN the default we ensure these previous versions are compatible,
    and will default to using EN correctly.

    buf:lint:ignore ENUM_ZERO_VALUE_SUFFIX
    """

    # English
    EN = ("EN", 0)
    # Japanese
    JA = ("JA", 1)
    # French
    FR = ("FR", 2)
    # German
    DE = ("DE", 3)
    # Spanish
    ES = ("ES", 4)
    # Italian
    IT = ("IT", 5)
    # Arabic
    AR = ("AR", 6)
    # Czech
    CS = ("CS", 7)
    # Portuguese
    PT = ("PT", 8)
    # Dutch
    NL = ("NL", 9)


class ObjectiveSubCategory(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    THEFT = ("THEFT", 1)
    POISONING = ("POISONING", 2)
    STALKING = ("STALKING", 4)
    TERRORISM = ("TERRORISM", 5)
    BOMB = ("BOMB", 6)
    MURDER = ("MURDER", 7)
    PII_US_SSN = ("PII_US_SSN", 8)
    PII_PHONE_NUMBER = ("PII_PHONE_NUMBER", 9)
    PII_CREDIT_CARD_NUMBER = ("PII_CREDIT_CARD_NUMBER", 10)
    PII_EMAIL = ("PII_EMAIL", 11)
    PII_US_PASSPORT_NUMBER = ("PII_US_PASSPORT_NUMBER", 12)
    PIRACY = ("PIRACY", 13)
    VIRUS = ("VIRUS", 15)
    MISINFORMATION = ("MISINFORMATION", 16)
    FINANCIAL_ADVICE = ("FINANCIAL_ADVICE", 17)
    PII = ("PII", 18)
    PROMPT_EXTRACTION = ("PROMPT_EXTRACTION", 19)
    COPYRIGHT_EXTRACTION = ("COPYRIGHT_EXTRACTION", 21)
    LONG_PROMPTS = ("LONG_PROMPTS", 22)
    DRUGS = ("DRUGS", 24)
    SUICIDE = ("SUICIDE", 25)
    IDENTITY_THEFT = ("IDENTITY_THEFT", 26)
    ANIMAL_VIOLENCE = ("ANIMAL_VIOLENCE", 27)
    POLITICAL_OPINIONS = ("POLITICAL_OPINIONS", 28)
    BRANDED_CONTENT = ("BRANDED_CONTENT", 29)
    BULLYING = ("BULLYING", 30)
    CELEBRITY_PII = ("CELEBRITY_PII", 31)
    CHEATING = ("CHEATING", 32)
    CHILD_SEXUAL_ABUSE_MATERIAL = ("CHILD_SEXUAL_ABUSE_MATERIAL", 33)
    ROLE_PLAYING = ("ROLE_PLAYING", 34)
    DISABILITIES = ("DISABILITIES", 35)
    TROLLING = ("TROLLING", 36)
    ECONOMIC_CLASS = ("ECONOMIC_CLASS", 37)
    EMOTIONAL_ABUSE = ("EMOTIONAL_ABUSE", 38)
    FIREARMS = ("FIREARMS", 39)
    HUMAN_EXPLOITATION = ("HUMAN_EXPLOITATION", 40)
    IMMIGRATION_STATUS = ("IMMIGRATION_STATUS", 41)
    IMPERSONATION_IMPOSTOR_CONTENT = ("IMPERSONATION_IMPOSTOR_CONTENT", 42)
    INTELLECTUAL_PROPERTY_PIRACY = ("INTELLECTUAL_PROPERTY_PIRACY", 43)
    LOGOS = ("LOGOS", 44)
    MARITAL_STATUS = ("MARITAL_STATUS", 45)
    MOVIE_QUOTES = ("MOVIE_QUOTES", 46)
    PERSONAL_IDENTIFICATION_NUMBERS = ("PERSONAL_IDENTIFICATION_NUMBERS", 47)
    PHISHING = ("PHISHING", 48)
    PLAGIARISM = ("PLAGIARISM", 49)
    PORNOGRAPHIC_DEPICTIONS = ("PORNOGRAPHIC_DEPICTIONS", 50)
    RELIGIOUS_BELIEFS = ("RELIGIOUS_BELIEFS", 51)
    RISKY_FINANCIAL_PRACTICES = ("RISKY_FINANCIAL_PRACTICES", 52)
    RISKY_PRANKS = ("RISKY_PRANKS", 53)
    SCAMS = ("SCAMS", 54)
    SONG_LYRICS = ("SONG_LYRICS", 55)
    SPAM = ("SPAM", 56)
    SURVEILLANCE = ("SURVEILLANCE", 57)
    SYSTEMIC_RACISM = ("SYSTEMIC_RACISM", 58)
    THREATS_AND_INTIMIDATION = ("THREATS_AND_INTIMIDATION", 59)
    TOXIC_CHEMICALS = ("TOXIC_CHEMICALS", 60)
    UNSAFE_HEALTH_PRACTICES = ("UNSAFE_HEALTH_PRACTICES", 61)
    WAR_CRIMES = ("WAR_CRIMES", 62)
    WORKPLACE_DISCRIMINATION = ("WORKPLACE_DISCRIMINATION", 63)
    FUNCTION_CALL_EXTRACTION = ("FUNCTION_CALL_EXTRACTION", 64)
    MALWARE_VIRUS = ("MALWARE_VIRUS", 65)
    VULN_EXPLOIT = ("VULN_EXPLOIT", 66)
    RANSOMWARE_OPS = ("RANSOMWARE_OPS", 67)
    NETWORK_ATTACK_OPS = ("NETWORK_ATTACK_OPS", 68)
    SOCIAL_ENGG = ("SOCIAL_ENGG", 69)
    MALICIOUS_INFRA_OPS = ("MALICIOUS_INFRA_OPS", 70)
    COMPROMISED_ASSET_TRADE = ("COMPROMISED_ASSET_TRADE", 71)
    NUCLEAR_THREAT = ("NUCLEAR_THREAT", 72)
    BIO_WEAPON = ("BIO_WEAPON", 73)
    DOMESTIC_ABUSE = ("DOMESTIC_ABUSE", 74)
    TORTURE_METHODS = ("TORTURE_METHODS", 75)
    BOMB_THREATS = ("BOMB_THREATS", 76)
    VIOLENCE_OR_ASSAULT = ("VIOLENCE_OR_ASSAULT", 77)
    VIOLENT_REVOLT = ("VIOLENT_REVOLT", 78)
    MASS_ATTACK = ("MASS_ATTACK", 79)
    FIREARMS_WEAPONS_MAKING = ("FIREARMS_WEAPONS_MAKING", 80)
    FIREARMS_WEAPONS_GENERIC = ("FIREARMS_WEAPONS_GENERIC", 81)
    SWATTING_ATTACK = ("SWATTING_ATTACK", 82)
    ANIMAL_ABUSE = ("ANIMAL_ABUSE", 83)
    RACISM = ("RACISM", 84)
    HATE_SPEECH = ("HATE_SPEECH", 85)
    RELIGIOUS_BIAS = ("RELIGIOUS_BIAS", 86)
    ECONOMY_CLASS_BIAS = ("ECONOMY_CLASS_BIAS", 87)
    DISABILITY_BIAS = ("DISABILITY_BIAS", 88)
    WORKPLACE_BIAS = ("WORKPLACE_BIAS", 89)
    THREATS_INTIMIDATION = ("THREATS_INTIMIDATION", 90)
    HUMAN_EXPLOIT = ("HUMAN_EXPLOIT", 91)
    CYBERBULLYING = ("CYBERBULLYING", 92)
    SOCIAL_MEDIA_HARASSMENT = ("SOCIAL_MEDIA_HARASSMENT", 93)
    SEXUAL_CONTENT = ("SEXUAL_CONTENT", 94)
    SEXUAL_HARASSMENT = ("SEXUAL_HARASSMENT", 95)
    CHILD_SEX_ABUSE = ("CHILD_SEX_ABUSE", 96)
    SEXUAL_ABUSE = ("SEXUAL_ABUSE", 97)
    SEXTORTION = ("SEXTORTION", 98)
    SEXUAL_ROLEPLAY = ("SEXUAL_ROLEPLAY", 99)
    SEXUAL_SERVICES = ("SEXUAL_SERVICES", 100)
    SEXUAL_VULGARITY = ("SEXUAL_VULGARITY", 101)
    GENERAL_VULGARITY = ("GENERAL_VULGARITY", 102)
    VIOLENT_PROFANITY = ("VIOLENT_PROFANITY", 103)
    CODED_PROFANITY = ("CODED_PROFANITY", 104)
    ORGAN_TRAFFICKING = ("ORGAN_TRAFFICKING", 105)
    GOLD_TRAFFICKING = ("GOLD_TRAFFICKING", 106)
    SMUGGLING = ("SMUGGLING", 107)
    WEAPONS_TRAFFICKING = ("WEAPONS_TRAFFICKING", 108)
    BANK_FRAUD = ("BANK_FRAUD", 109)
    INVESTMENT_FRAUD = ("INVESTMENT_FRAUD", 110)
    CRYPTO_FRAUD = ("CRYPTO_FRAUD", 111)
    FINANCIAL_SCAM = ("FINANCIAL_SCAM", 112)
    ILLICIT_FINANCIAL_ADVICE = ("ILLICIT_FINANCIAL_ADVICE", 113)
    IMMIGRATION_ABUSE = ("IMMIGRATION_ABUSE", 114)
    IMMIGRATION_SCAM = ("IMMIGRATION_SCAM", 115)
    LAND_EXPLOITATION = ("LAND_EXPLOITATION", 116)
    FOREST_EXPLOITATION = ("FOREST_EXPLOITATION", 117)
    WATER_EXPLOITATION = ("WATER_EXPLOITATION", 118)
    POLLUTION_GENERIC = ("POLLUTION_GENERIC", 119)
    ECOSYSTEM_DISRUPTION = ("ECOSYSTEM_DISRUPTION", 120)
    TECH_SUPPORT_SCAM = ("TECH_SUPPORT_SCAM", 121)
    DIGITAL_SPAM = ("DIGITAL_SPAM", 122)
    PROPRIETARY_CODE_ABUSE = ("PROPRIETARY_CODE_ABUSE", 123)
    REVERSE_ENGINEERING_CODE = ("REVERSE_ENGINEERING_CODE", 124)
    LICENSE_BYPASS_SPOOFING = ("LICENSE_BYPASS_SPOOFING", 125)
    COUNTERFEITING = ("COUNTERFEITING", 126)
    FAKE_SERVICES = ("FAKE_SERVICES", 127)
    FOOD_FRAUD = ("FOOD_FRAUD", 128)
    CHEATING_OR_PLAGIARISM = ("CHEATING_OR_PLAGIARISM", 129)
    EVIDENCE_TAMPERING = ("EVIDENCE_TAMPERING", 130)
    TERROR_PROPAGANDA = ("TERROR_PROPAGANDA", 131)
    TERROR_GROUP = ("TERROR_GROUP", 132)
    TERROR_ACTIONS = ("TERROR_ACTIONS", 133)
    MODEL_INFORMATION_EXTRACTION = ("MODEL_INFORMATION_EXTRACTION", 134)
    DISINFORMATION = ("DISINFORMATION", 135)
    IMPERSONATION_IMPOSTER_CONTENT = ("IMPERSONATION_IMPOSTER_CONTENT", 136)
    SUICIDE_METHODS = ("SUICIDE_METHODS", 137)
    SUICIDE_ENCOURAGE = ("SUICIDE_ENCOURAGE", 138)
    SELFHARM_TECHNIQUE = ("SELFHARM_TECHNIQUE", 139)
    SUICIDE_PACT = ("SUICIDE_PACT", 140)
    SUICIDE_NOTE = ("SUICIDE_NOTE", 141)
    COPYRIGHT_CONTENT = ("COPYRIGHT_CONTENT", 142)
    SONGS_PIRACY_AND_INFRINGEMENT = ("SONGS_PIRACY_AND_INFRINGEMENT", 143)
    MOVIES_PIRACY_AND_INFRINGEMENT = ("MOVIES_PIRACY_AND_INFRINGEMENT", 144)
    TV_CONTENT_PIRACY_AND_INFRINGEMENT = ("TV_CONTENT_PIRACY_AND_INFRINGEMENT", 145)
    LITERATURE_PIRACY_AND_INFRINGEMENT = ("LITERATURE_PIRACY_AND_INFRINGEMENT", 146)
    UNSAFE_ACTIONS = ("UNSAFE_ACTIONS", 147)
    DANGEROUS_GAMES = ("DANGEROUS_GAMES", 148)
    UNSAFE_MEDS_ADVICE = ("UNSAFE_MEDS_ADVICE", 149)
    UNSAFE_MEDICAL_PROCEDURES = ("UNSAFE_MEDICAL_PROCEDURES", 150)
    ILLEGAL_REPRODUCTIVE_PRACTICES = ("ILLEGAL_REPRODUCTIVE_PRACTICES", 151)
    PERSONAL_IDENTIFICATION_NUMBER = ("PERSONAL_IDENTIFICATION_NUMBER", 152)
    TARGETED_PERSON_PII = ("TARGETED_PERSON_PII", 153)
    HACKING = ("HACKING", 154)


class Threat(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    VIOLENCE_UNSAFE_ACTIONS = ("VIOLENCE_UNSAFE_ACTIONS", 1)
    ILLEGAL_ACTIVITIES = ("ILLEGAL_ACTIVITIES", 2)
    PRIVACY_ATTACKS = ("PRIVACY_ATTACKS", 3)
    SENSITIVE_INFORMATION_DISCLOSURE = ("SENSITIVE_INFORMATION_DISCLOSURE", 4)
    FACTUAL_INCONSISTENCIES = ("FACTUAL_INCONSISTENCIES", 6)
    MALICIOUS_CODE_GENERATION = ("MALICIOUS_CODE_GENERATION", 7)
    META_PROMPT_EXTRACTION = ("META_PROMPT_EXTRACTION", 8)
    SELF_HARM = ("SELF_HARM", 9)
    UNETHICAL_ACTIONS = ("UNETHICAL_ACTIONS", 10)
    CONTROVERSIAL_TOPICS = ("CONTROVERSIAL_TOPICS", 11)
    COPYRIGHT_INFRINGEMENT = ("COPYRIGHT_INFRINGEMENT", 12)
    DISINFORMATION = ("DISINFORMATION", 13)
    HARASSMENT = ("HARASSMENT", 14)
    HATE_SPEECH_AND_DISCRIMINATION = ("HATE_SPEECH_AND_DISCRIMINATION", 15)
    JAILBREAKS = ("JAILBREAKS", 16)
    MODEL_DENIAL_OF_SERVICE = ("MODEL_DENIAL_OF_SERVICE", 17)
    SEXUAL_CONTENT = ("SEXUAL_CONTENT", 18)
    SOCIAL_ENGINEERING = ("SOCIAL_ENGINEERING", 19)
    VIOLENCE_PUBLIC_SAFETY = ("VIOLENCE_PUBLIC_SAFETY", 20)
    ENVIRONMENTAL_HARM = ("ENVIRONMENTAL_HARM", 21)
    FINANCIAL_HARM = ("FINANCIAL_HARM", 22)
    HALLUCINATIONS = ("HALLUCINATIONS", 23)
    HATE_SPEECH = ("HATE_SPEECH", 24)
    IP_THEFT = ("IP_THEFT", 25)
    MODEL_EXTRACTION = ("MODEL_EXTRACTION", 26)
    NON_VIOLENT_CRIME = ("NON_VIOLENT_CRIME", 27)
    PII = ("PII", 28)
    PROFANITY = ("PROFANITY", 29)
    SCAMS_DECEPTION = ("SCAMS_DECEPTION", 30)
    SEXUAL_CONTENT_EXPLOITATION = ("SEXUAL_CONTENT_EXPLOITATION", 31)
    SOCIAL_DIVISION_POLARIZATION = ("SOCIAL_DIVISION_POLARIZATION", 32)
    SPECIALIZED_ADVICE = ("SPECIALIZED_ADVICE", 33)


class AttackObjective(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    ABUSE = ("ABUSE", 1)
    PRIVACY = ("PRIVACY", 2)
    AVAILABILITY = ("AVAILABILITY", 3)
    INTEGRITY = ("INTEGRITY", 4)


class Objective(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    GOAL_HIJACKING = ("GOAL_HIJACKING", 1)
    JAILBREAK = ("JAILBREAK", 2)
    MULTI_MODAL_CROSS_MODAL_RISKS = ("MULTI_MODAL_CROSS_MODAL_RISKS", 3)


class Technique(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    DIRECT_PROMPT_INJECTION = ("DIRECT_PROMPT_INJECTION", 1)
    JAILBREAK = ("JAILBREAK", 2)
    FUSION_PAYLOAD_SPLIT = ("FUSION_PAYLOAD_SPLIT", 3)
    MULTI_MODAL_INJECTION_AND_MANIPULATION = ("MULTI_MODAL_INJECTION_AND_MANIPULATION", 4)


class SubTechnique(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    OBFUSCATION = ("OBFUSCATION", 1)
    INSTRUCTION_MANIPULATION = ("INSTRUCTION_MANIPULATION", 2)
    SEMANTIC_MANIPULATION = ("SEMANTIC_MANIPULATION", 3)
    CONTEXT_MANIPULATION = ("CONTEXT_MANIPULATION", 4)
    TOKEN_EXPLOITATION = ("TOKEN_EXPLOITATION", 5)
    CHAINED_PAYLOAD_EXECUTION = ("CHAINED_PAYLOAD_EXECUTION", 6)
    IMAGE_TEXT_INJECTION = ("IMAGE_TEXT_INJECTION", 7)
    AUDIO_COMMAND_INJECTION = ("AUDIO_COMMAND_INJECTION", 8)


class ContentCategory(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    SAFETY_HARMS_AND_TOXICITY = ("SAFETY_HARMS_AND_TOXICITY", 1)
    CYBERSECURITY_AND_HACKING = ("CYBERSECURITY_AND_HACKING", 2)
    PRIVACY_ATTACKS = ("PRIVACY_ATTACKS", 4)
    INTELLECTUAL_PROPERTY_COMPROMISE = ("INTELLECTUAL_PROPERTY_COMPROMISE", 5)
    INTEGRITY_COMPROMISE = ("INTEGRITY_COMPROMISE", 6)
    SPECIALIZED_ADVICE = ("SPECIALIZED_ADVICE", 7)


class ContentType(_ProtoEnum):
    UNSPECIFIED = ("UNSPECIFIED", 0)
    CYBER_ABUSE = ("CYBER_ABUSE", 2)
    DISINFORMATION = ("DISINFORMATION", 3)
    ENVIRONMENTAL_HARM = ("ENVIRONMENTAL_HARM", 4)
    FINANCIAL_HARM = ("FINANCIAL_HARM", 5)
    HALLUCINATIONS_MISINFORMATION = ("HALLUCINATIONS_MISINFORMATION", 6)
    HARASSMENT = ("HARASSMENT", 7)
    HATE_SPEECH = ("HATE_SPEECH", 8)
    INTELLECTUAL_PROPERTY_INFRINGEMENT = ("INTELLECTUAL_PROPERTY_INFRINGEMENT", 9)
    MALWARE_EXPLOITS = ("MALWARE_EXPLOITS", 10)
    NON_VIOLENT_CRIME = ("NON_VIOLENT_CRIME", 11)
    PII_PHI_PCI = ("PII_PHI_PCI", 12)
    PROFANITY = ("PROFANITY", 13)
    SCAMS_DECEPTION = ("SCAMS_DECEPTION", 14)
    SELF_HARM = ("SELF_HARM", 15)
    SEXUAL_CONTENT_EXPLOITATION = ("SEXUAL_CONTENT_EXPLOITATION", 16)
    SOCIAL_DIVISION_POLARIZATION = ("SOCIAL_DIVISION_POLARIZATION", 17)
    UNAUTHORIZED_FINANCIAL_ADVICE = ("UNAUTHORIZED_FINANCIAL_ADVICE", 19)
    VIOLENCE_PUBLIC_SAFETY_THREAT = ("VIOLENCE_PUBLIC_SAFETY_THREAT", 20)
    CONFIDENTIAL_DATA = ("CONFIDENTIAL_DATA", 22)
    UNAUTHORIZED_MEDICAL_ADVICE = ("UNAUTHORIZED_MEDICAL_ADVICE", 23)
    PRIVACY_ATTACKS = ("PRIVACY_ATTACKS", 24)
    SPECIALIZED_ADVICE = ("SPECIALIZED_ADVICE", 25)
    MODEL_EXTRACTION = ("MODEL_EXTRACTION", 26)
    SOCIAL_ENGINEERING = ("SOCIAL_ENGINEERING", 27)
    META_PROMPT_EXTRACTION = ("META_PROMPT_EXTRACTION", 28)


class ValidateResponse(_ProtoModel):
    """
    ValidateResponse is the response for the Validate (V3) endpoint.
    """

    pass


class ValidateModelV3Request(_ProtoModel):
    """
    ValidateModelV3Request is the request for the ValidateModelV3 endpoint.
    It runs a batch of attacks against the customer target.
    """

    # Parameters for connecting to the customer target.
    model_connection: "ModelConnectionSpec | None" = _Field(
        default=None,
        description="Parameters for connecting to the customer target.",
    )
    # The tenant ID of the user. Used for logging.
    tenant_id: str = _Field(
        default="",
        description="The tenant ID of the user. Used for logging.",
    )
    # The task ID assigned by the validation manager. Used for logging.
    task_id: str = _Field(
        default="",
        description="The task ID assigned by the validation manager. Used for logging.",
    )
    # The batch of attacks to run against the model.
    attacks: "list[AttackExampleV3]" = _Field(
        default_factory=list,
        description="The batch of attacks to run against the model.",
    )
    # The language of the generative validation test.
    language: "Language | None" = _Field(
        default=None,
        description="The language of the generative validation test.",
    )


class ValidateModelV3Response(_ProtoModel):
    """
    ValidateModelV3Response is the response for the ValidateModelV3 endpoint.
    Contains per-attack results for the submitted batch.
    """

    # All the validation results for the submitted batch of attacks.
    results: "list[AttackResultInfo]" = _Field(
        default_factory=list,
        description="All the validation results for the submitted batch of attacks.",
    )


class AttackResultInfo(_ProtoModel):
    # Identifier for the attack example used to create this result. For multi-turn
    # attacks that fan out per strategy, this is the per-strategy id
    # (mt-{attack_id}-{strategy_slug}) so each strategy persists as its own row.
    attack_example_id: str = _Field(
        default="",
        description="Identifier for the attack example used to create this result. For multi-turn\nattacks that fan out per strategy, this is the per-strategy id\n(mt-{attack_id}-{strategy_slug}) so each strategy persists as its own row.",
    )
    # Whether the attack succeeded/failed/errored out.
    result_status: "AttackResult | None" = _Field(
        default=None,
        description="Whether the attack succeeded/failed/errored out.",
    )
    # The output from the customer target. If there was an error from the
    # customer target, the error message will be sent as part of this field.
    target_output: str = _Field(
        default="",
        description="The output from the customer target. If there was an error from the\ncustomer target, the error message will be sent as part of this field.",
    )
    # The procedure (method used to conduct the attack). For multi-turn attacks
    # that fan out into one result per strategy, this is the per-strategy
    # conversational strategy. Empty for single-turn attacks, where the caller
    # uses the attack's own procedure.
    procedure: str = _Field(
        default="",
        description="The procedure (method used to conduct the attack). For multi-turn attacks\nthat fan out into one result per strategy, this is the per-strategy\nconversational strategy. Empty for single-turn attacks, where the caller\nuses the attack's own procedure.",
    )


class ValidateModelRequest(_ProtoModel):
    """
    ValidateModelRequest is the request for the ValidateModel endpoint
    """

    # Parameters for connecting to the user's generative model.
    model_connection: "ModelConnectionSpec | None" = _Field(
        default=None,
        description="Parameters for connecting to the user's generative model.",
    )
    # The prompt bank to use.
    prompt_bank: "PromptBank | None" = _Field(
        default=None,
        description="The prompt bank to use.",
    )
    # The system prompt that is currently active on the provided endpoint. If this is not set, system prompt extraction
    # tests will be skipped.
    system_prompt: str = _Field(
        default="",
        description="The system prompt that is currently active on the provided endpoint. If this is not set, system prompt extraction\ntests will be skipped.",
    )
    # Will not be saved to the database, logged in plaintext, etc.
    model_output_is_sensitive: bool = _Field(
        default=False,
        description="Will not be saved to the database, logged in plaintext, etc.",
    )
    # The language of the generative validation test.
    language: "Language | None" = _Field(
        default=None,
        description="The language of the generative validation test.",
    )
    # The tenant ID of the user.
    tenant_id: str = _Field(
        default="",
        description="The tenant ID of the user.",
    )
    # The ID of the validation config.
    config_id: str = _Field(
        default="",
        description="The ID of the validation config.",
    )
    # The task ID assigned by the validation manager.
    task_id: str = _Field(
        default="",
        description="The task ID assigned by the validation manager.",
    )
    # Whether multi-turn is enabled for the attacks.
    multi_turn_enabled: bool = _Field(
        default=False,
        description="Whether multi-turn is enabled for the attacks.",
    )
    # DEPRECATED: Model analyzer choice is no longer supported. The method (or
    # model) to use to analyze customer model respones (whether or not an attack
    # was successful).
    model_response_analyzer: "ModelResponseAnalyzer | None" = _Field(
        default=None,
        description="DEPRECATED: Model analyzer choice is no longer supported. The method (or\nmodel) to use to analyze customer model respones (whether or not an attack\nwas successful).",
    )
    # Custom attacks sent by the control plane created from user provided goals
    custom_goals: "list[AttackExample]" = _Field(
        default_factory=list,
        description="Custom attacks sent by the control plane created from user provided goals",
    )
    # If provided, only attacks belonging to the listed content categorie will
    # be conducted. If the list is empty, all attacks will be conducted.
    content_categories: "list[ContentCategory]" = _Field(
        default_factory=list,
        description="If provided, only attacks belonging to the listed content categorie will\nbe conducted. If the list is empty, all attacks will be conducted.",
    )


class ValidateResult(_ProtoModel):
    """
    ValidateResult is the validation result for a single AttackExample
    """

    # The attack example for this result
    attack_example: "AttackExample | None" = _Field(
        default=None,
        description="The attack example for this result",
    )
    # The output from the customer's LLM
    model_output: str = _Field(
        default="",
        description="The output from the customer's LLM",
    )
    # Whether the attack succeeded/failed/etc.
    result: "AttackResult | None" = _Field(
        default=None,
        description="Whether the attack succeeded/failed/etc.",
    )
    # The security risk level of this test.
    severity: "Severity | None" = _Field(
        default=None,
        description="The security risk level of this test.",
    )
    # If there was an error, further details are displayed here.
    error_message: str = _Field(
        default="",
        description="If there was an error, further details are displayed here.",
    )


class ValidateModelResponse(_ProtoModel):
    """
    ValidateModelResponse is the response for the ValidateModel endpoint
    """

    # All the validation results for the current batch.
    results: "list[ValidateResult]" = _Field(
        default_factory=list,
        description="All the validation results for the current batch.",
    )
    # The total number of prompts tested, across all batches.
    # This is used by the CP to track progress of the validation.
    total_num_prompts: int = _Field(
        default=0,
        description="The total number of prompts tested, across all batches.\nThis is used by the CP to track progress of the validation.",
    )


class ValidateModelResponseV2(_ProtoModel):
    """
    ValidateModelResponseV2 only returns an error
    """

    pass


class RedTeamTestRequest(_ProtoModel):
    """
    Request to run a red team test against a model.
    """

    # Assigned by the validation manager (control plane).
    job_id: str = _Field(
        default="",
        description="Assigned by the validation manager (control plane).",
    )
    # Parameters for connecting to the user's generative model.
    customer_model_connection: "ModelConnectionSpec | None" = _Field(
        default=None,
        description="Parameters for connecting to the user's generative model.",
    )
    # Will not be saved to the database, logged in plaintext, etc.
    model_output_is_sensitive: bool = _Field(
        default=False,
        description="Will not be saved to the database, logged in plaintext, etc.",
    )
    # The language of the generative validation test.
    language: "Language | None" = _Field(
        default=None,
        description="The language of the generative validation test.",
    )
    # The system prompt that is currently active on the provided endpoint.
    system_prompt: str = _Field(
        default="",
        description="The system prompt that is currently active on the provided endpoint.",
    )
    # Custom goals for adaptive red teaming. Each entry's .intent field
    # provides a goal string; other fields carry taxonomy metadata.
    custom_goals: "list[AttackExample]" = _Field(
        default_factory=list,
        description="Custom goals for adaptive red teaming. Each entry's .intent field\nprovides a goal string; other fields carry taxonomy metadata.",
    )
    # Industry vertical to use when generating attacks. Optional.
    # UNSPECIFIED falls back to INDUSTRY_DEFAULT inside the data plane.
    industry: "Industry | None" = _Field(
        default=None,
        description="Industry vertical to use when generating attacks. Optional.\nUNSPECIFIED falls back to INDUSTRY_DEFAULT inside the data plane.",
    )


class RedTeamTestResponse(_ProtoModel):
    """
    Response to confirm whether the automated red teaming started or not.
    """

    pass


class AttackAsset(_ProtoModel):
    """
    AttackAsset carries a single media payload (image or audio) for a
    multimodal attack.
    """

    # IANA MIME type of the payload, e.g. "image/png", "image/jpeg",
    # "audio/wav", "audio/mpeg".
    mime_type: str = _Field(
        default="",
        description='IANA MIME type of the payload, e.g. "image/png", "image/jpeg",\n"audio/wav", "audio/mpeg".',
    )
    # Local path to the stored media asset.
    path: str | None = _Field(
        default=None,
        description='Local path to the stored media asset.\nOnly one of the fields can be specified with: ["path", "content"] (oneof source)',
    )
    # Raw bytes of the media content.
    content: bytes | None = _Field(
        default=None,
        description='Raw bytes of the media content.\nOnly one of the fields can be specified with: ["path", "content"] (oneof source)',
    )
    # Hash (SHA-256) of the media content.
    asset_sha256: str = _Field(
        default="",
        description="Hash (SHA-256) of the media content.",
    )
    # Size of the raw media in bytes.
    size_bytes: ProtoUInt64 = _Field(
        default=0,
        description="Size of the raw media in bytes.",
    )

    @_model_validator(mode="after")
    def _validate_oneof_source(self) -> "AttackAsset":
        _set = [f for f in ("path", "content") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'source': only one field may be set, got {_set!r}")
        return self


class AttackExample(_ProtoModel):
    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # e.g. bomb, murder
    objective_sub_category: "ObjectiveSubCategory | None" = _Field(
        default=None,
        description="e.g. bomb, murder",
    )
    # The actual prompt used for testing a model
    prompt: str = _Field(
        default="",
        description="The actual prompt used for testing a model",
    )
    # The base intent that the prompt was produced from
    intent: str = _Field(
        default="",
        description="The base intent that the prompt was produced from",
    )
    # e.g. KeyboardCharAugmenter, Base64Encoder
    technique: str = _Field(
        default="",
        description="e.g. KeyboardCharAugmenter, Base64Encoder",
    )
    # e.g. "Sensitive Content and Topics", "Model Denial of Service"
    harm_category: str = _Field(
        default="",
        description='e.g. "Sensitive Content and Topics", "Model Denial of Service"',
    )
    # e.g. abuse, privacy
    attack_objective: "AttackObjective | None" = _Field(
        default=None,
        description="e.g. abuse, privacy",
    )
    # e.g. violence, data extraction, self-harm
    threat: "Threat | None" = _Field(
        default=None,
        description="e.g. violence, data extraction, self-harm",
    )
    # List of the OWASP AI risk standards associated with the attacks in these results.
    owasp_standards: list[str] = _Field(
        default_factory=list,
        description="List of the OWASP AI risk standards associated with the attacks in these results.",
    )
    # List of the NIST AI risk standards associated with the attacks in these results.
    nist_standards: list[str] = _Field(
        default_factory=list,
        description="List of the NIST AI risk standards associated with the attacks in these results.",
    )
    # List of the MITRE AI risk standards associated with the attacks in these results.
    mitre_standards: list[str] = _Field(
        default_factory=list,
        description="List of the MITRE AI risk standards associated with the attacks in these results.",
    )
    # Additional information about the attack, such as copyright text.  This will evaluate to a valid JSON string.
    detection_context: str = _Field(
        default="",
        description="Additional information about the attack, such as copyright text.  This will evaluate to a valid JSON string.",
    )
    # IMPORTANT: This ID should only be used to update results during a validation test run.
    # There is no guarantee of uniqueness between validation test runs or prompt bank
    # versions.
    id_: str = _Field(
        default="",
        description="IMPORTANT: This ID should only be used to update results during a validation test run.\nThere is no guarantee of uniqueness between validation test runs or prompt bank\nversions.",
        alias="id",
    )
    # This field determines if multi-turn logic is used for the attack.
    attack_type: "AttackType | None" = _Field(
        default=None,
        description="This field determines if multi-turn logic is used for the attack.",
    )
    # The following fields make up the new attack bank taxonomy as of January 2026.
    # The overall objective of the attack prompt.
    objective: "Objective | None" = _Field(
        default=None,
        description="The following fields make up the new attack bank taxonomy as of January 2026.\nThe overall objective of the attack prompt.",
    )
    # Named technique_type to prevent name overlap with previous technique
    # Broad categorization of the attack prompt.
    technique_type: "Technique | None" = _Field(
        default=None,
        description="Named technique_type to prevent name overlap with previous technique\nBroad categorization of the attack prompt.",
    )
    # More granular categorization of the attack prompt.
    sub_technique: "SubTechnique | None" = _Field(
        default=None,
        description="More granular categorization of the attack prompt.",
    )
    # The method used to conduct the attack. This is a string because there are
    # numerous methods and they are guaranteed to frequently change over time.
    procedure: str = _Field(
        default="",
        description="The method used to conduct the attack. This is a string because there are\nnumerous methods and they are guaranteed to frequently change over time.",
    )
    # Categorization of the type of content included in the attack.
    content_category: "ContentCategory | None" = _Field(
        default=None,
        description="Categorization of the type of content included in the attack.",
    )
    # More granular categorization of the content included in the attack.
    content_type: "ContentType | None" = _Field(
        default=None,
        description="More granular categorization of the content included in the attack.",
    )
    # Hash (SHA-256) of the prompt + various metadata.
    prompt_sha256: str = _Field(
        default="",
        description="Hash (SHA-256) of the prompt + various metadata.",
    )
    # The modality of this attack. Defaults to TEXT (UNSPECIFIED is treated as
    # TEXT).
    modality: "AttackModality | None" = _Field(
        default=None,
        description="The modality of this attack. Defaults to TEXT (UNSPECIFIED is treated as\nTEXT).",
    )
    # Media assets for this attack. Empty for text-only attacks.
    assets: "list[AttackAsset]" = _Field(
        default_factory=list,
        description="Media assets for this attack. Empty for text-only attacks.",
    )


class AttackExampleV3(_ProtoModel):
    """
    AttackExampleV3 is a lightweight attack reference passed to ValidateModelV3.
    Unlike AttackExample, it carries only the minimum needed to execute an
    attack and correlate its result back to the validation manager.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # IMPORTANT: This ID should only be used to tie a result back to this attack
    # example. There is no guarantee of uniqueness between validation test runs.
    id_: str = _Field(
        default="",
        description="IMPORTANT: This ID should only be used to tie a result back to this attack\nexample. There is no guarantee of uniqueness between validation test runs.",
        alias="id",
    )
    # The actual prompt used for testing a model.
    prompt: str = _Field(
        default="",
        description="The actual prompt used for testing a model.",
    )
    # The base intent that the prompt was produced from.
    intent: str = _Field(
        default="",
        description="The base intent that the prompt was produced from.",
    )
    # Determines whether single-turn, multi-turn or custom goal logic is used to
    # execute this attack against the target model.
    attack_type: "AttackType | None" = _Field(
        default=None,
        description="Determines whether single-turn, multi-turn or custom goal logic is used to\nexecute this attack against the target model.",
    )
    # The modality of this attack. Defaults to TEXT (UNSPECIFIED is treated as
    # TEXT for backward compatibility with existing text-only callers).
    modality: "AttackModality | None" = _Field(
        default=None,
        description="The modality of this attack. Defaults to TEXT (UNSPECIFIED is treated as\nTEXT for backward compatibility with existing text-only callers).",
    )
    # Media payloads for image/audio attacks. Empty for text-only
    # attacks. `prompt` may still be set alongside media for multimodal attacks
    # (e.g. an adversarial image plus an accompanying instruction).
    assets: "list[AttackAsset]" = _Field(
        default_factory=list,
        description="Media payloads for image/audio attacks. Empty for text-only\nattacks. `prompt` may still be set alongside media for multimodal attacks\n(e.g. an adversarial image plus an accompanying instruction).",
    )


class HttpConnectionSpec(_ProtoModel):
    """
    HttpConnectionSpec is how a user defines information for how to configure an http request to an LLM.
    """

    # The url of the model
    url: str = _Field(
        default="",
        description="The url of the model",
    )
    # A json path specifying where in the response json payload we can find the LLM's response response string. Note that
    # the path must point to a string value in the json payload. Whitespace and other special characters can be encoded
    # as unicode (\u0020). Periods in json fields can be escaped with a backslash.
    response_json_path: str = _Field(
        default="",
        description="A json path specifying where in the response json payload we can find the LLM's response response string. Note that\nthe path must point to a string value in the json payload. Whitespace and other special characters can be encoded\nas unicode (\\u0020). Periods in json fields can be escaped with a backslash.",
    )
    # The body template which is sent to the model after updating by replacing {{prompt}} with different prompt attacks
    # within the struct. Only one {{prompt}} is currently supported.
    body_template: dict[str, _Any] | None = _Field(
        default=None,
        description="The body template which is sent to the model after updating by replacing {{prompt}} with different prompt attacks\nwithin the struct. Only one {{prompt}} is currently supported.",
    )
    # Headers that will be sent along with the request payload to the LLM endpoint. These headers can include
    # authentication.
    headers: dict[str, str] = _Field(
        default_factory=dict,
        description="Headers that will be sent along with the request payload to the LLM endpoint. These headers can include\nauthentication.",
    )
    # ExternalAPIProvider is the provider of the external http API endpoint that this connection is using.
    # This is used to determine how to parse the response from the particular provider.
    external_api_provider: "ExternalApiProvider | None" = _Field(
        default=None,
        description="ExternalAPIProvider is the provider of the external http API endpoint that this connection is using.\nThis is used to determine how to parse the response from the particular provider.",
    )
    # ClientID is defined by the OAuth provider when AI Validation is registered as an application.
    oauth_client_id: str = _Field(
        default="",
        description="ClientID is defined by the OAuth provider when AI Validation is registered as an application.",
    )
    # ClientSecret is defined by the OAuth provider when AI Validation is registered as an application.
    oauth_client_secret: str = _Field(
        default="",
        description="ClientSecret is defined by the OAuth provider when AI Validation is registered as an application.",
    )
    # TokenURL is the Oauth service's endpoint to acquire and refresh access tokens.
    oauth_token_url: str = _Field(
        default="",
        description="TokenURL is the Oauth service's endpoint to acquire and refresh access tokens.",
    )
    # Scopes are the permissions AI Validation needs to query the external API. The values are specific to the API
    # provider and OAuth service being used.
    oauth_scopes: list[str] = _Field(
        default_factory=list,
        description="Scopes are the permissions AI Validation needs to query the external API. The values are specific to the API\nprovider and OAuth service being used.",
    )
    # What model to append to our request body.
    model: str = _Field(
        default="",
        description="What model to append to our request body.",
    )
    # Whether the response_json_path is the new jmespath syntax or
    # still the old gjson syntax
    response_path_is_jmespath: bool = _Field(
        default=False,
        description="Whether the response_json_path is the new jmespath syntax or\nstill the old gjson syntax",
    )
    # Custom message request config for providers not in the ExternalApiProvider enum.
    message_request_config: "MessageRequestConfig | None" = _Field(
        default=None,
        description="Custom message request config for providers not in the ExternalApiProvider enum.",
    )
    # AWS SigV4 credentials. When set, outbound requests are signed with AWS SigV4.
    sigv4: "AwsSigV4Credentials | None" = _Field(
        default=None,
        description="AWS SigV4 credentials. When set, outbound requests are signed with AWS SigV4.",
    )
    # Whether the target endpoint returns a streaming response (e.g., SSE).
    is_streaming: bool = _Field(
        default=False,
        description="Whether the target endpoint returns a streaming response (e.g., SSE).",
    )


class RoleMap(_ProtoModel):
    """
    RoleMap defines how to map standard role types to provider-specific role values.
    All fields are optional - empty string means that role is not used or supported.
    """

    # The value to use for system role messages (e.g., "system", "system(top)")
    system: str = _Field(
        default="",
        description='The value to use for system role messages (e.g., "system", "system(top)")',
    )
    # The value to use for developer role messages (e.g., "developer", "system")
    developer: str = _Field(
        default="",
        description='The value to use for developer role messages (e.g., "developer", "system")',
    )
    # The value to use for user role messages (e.g., "user")
    user: str = _Field(
        default="",
        description='The value to use for user role messages (e.g., "user")',
    )
    # The value to use for assistant role messages (e.g., "assistant", "model")
    assistant: str = _Field(
        default="",
        description='The value to use for assistant role messages (e.g., "assistant", "model")',
    )
    # The value to use for tool role messages (e.g., "tool", "functionResponse")
    tool: str = _Field(
        default="",
        description='The value to use for tool role messages (e.g., "tool", "functionResponse")',
    )


class MessageRequestConfig(_ProtoModel):
    """
    MessageRequestConfig defines how to structure message-based requests sent to a target API.
    Used to build properly formatted request payloads for any LLM or agent provider
    (OpenAI, Anthropic, Gemini, etc.), including role mapping, system prompt placement,
    and content formatting for multi-turn conversations.
    """

    # The field name for the messages array in the request payload (e.g., "messages", "contents")
    container: str = _Field(
        default="",
        description='The field name for the messages array in the request payload (e.g., "messages", "contents")',
    )
    # How system messages are handled. Common values:
    # - "in_messages_as_role": system message is included in the messages array with a role
    # - "top_level_field": system message is a separate top-level field in the request
    system_placement: str = _Field(
        default="",
        description='How system messages are handled. Common values:\n- "in_messages_as_role": system message is included in the messages array with a role\n- "top_level_field": system message is a separate top-level field in the request',
    )
    # If system_placement is "top_level_field", this is the field name (e.g., "system", "system_instruction")
    system_field: str = _Field(
        default="",
        description='If system_placement is "top_level_field", this is the field name (e.g., "system", "system_instruction")',
    )
    # The field name for the role in each message object (e.g., "role")
    role_field: str = _Field(
        default="",
        description='The field name for the role in each message object (e.g., "role")',
    )
    # The field name for the content in each message object (e.g., "content")
    content_field: str = _Field(
        default="",
        description='The field name for the content in each message object (e.g., "content")',
    )
    # Mapping from standard role types to provider-specific role values
    role_map: "RoleMap | None" = _Field(
        default=None,
        description="Mapping from standard role types to provider-specific role values",
    )
    # The format of the content field. Common values:
    # - "string_only": content is always a plain string
    # - "parts_only": content is always an array of part objects
    # - "string_or_parts": content can be either a string or an array of parts
    content_shape: str = _Field(
        default="",
        description='The format of the content field. Common values:\n- "string_only": content is always a plain string\n- "parts_only": content is always an array of part objects\n- "string_or_parts": content can be either a string or an array of parts',
    )
    # The format of individual parts when content_shape is "parts_only".
    # - "text_only":   [{"text": "..."}]                    (Gemini, Bedrock Converse)
    # - "typed_text":  [{"type": "text", "text": "..."}]    (Anthropic)
    # Defaults to "text_only" when empty.
    part_format: str = _Field(
        default="",
        description='The format of individual parts when content_shape is "parts_only".\n- "text_only":   [{"text": "..."}]                    (Gemini, Bedrock Converse)\n- "typed_text":  [{"type": "text", "text": "..."}]    (Anthropic)\nDefaults to "text_only" when empty.',
    )


class WebsocketConnectionSpec(_ProtoModel):
    """
    WebsocketConnectionSpec is how a user defines information for how to configure a
    websocket connection to an LLM.
    """

    # The url of the websocket endpoint (ws:// or wss://)
    url: str = _Field(
        default="",
        description="The url of the websocket endpoint (ws:// or wss://)",
    )
    # A json path specifying where in the response json payload we can find the LLM's
    # response string. Note that the path must point to a string value in the json payload.
    # Whitespace and other special characters can be encoded as unicode (\u0020).
    # Periods in json fields can be escaped with a backslash.
    response_json_path: str = _Field(
        default="",
        description="A json path specifying where in the response json payload we can find the LLM's\nresponse string. Note that the path must point to a string value in the json payload.\nWhitespace and other special characters can be encoded as unicode (\\u0020).\nPeriods in json fields can be escaped with a backslash.",
    )
    # The body template which is sent to the model after updating by replacing
    # {{prompt}} with different prompt attacks within the struct. Only one {{prompt}}
    # is currently supported.
    body_template: dict[str, _Any] | None = _Field(
        default=None,
        description="The body template which is sent to the model after updating by replacing\n{{prompt}} with different prompt attacks within the struct. Only one {{prompt}}\nis currently supported.",
    )
    # Headers that will be sent along with the websocket connection handshake. These
    # headers can include authentication.
    headers: dict[str, str] = _Field(
        default_factory=dict,
        description="Headers that will be sent along with the websocket connection handshake. These\nheaders can include authentication.",
    )
    # Specifies how the websocket server sends responses.
    # Optional - if unspecified, the client reads a single message.
    response_type_config: "WebsocketResponseTypeConfig | None" = _Field(
        default=None,
        description="Specifies how the websocket server sends responses.\nOptional - if unspecified, the client reads a single message.",
    )
    # Whether the response_json_path is the new jmespath syntax or
    # still the old gjson syntax
    response_path_is_jmespath: bool = _Field(
        default=False,
        description="Whether the response_json_path is the new jmespath syntax or\nstill the old gjson syntax",
    )
    # AWS SigV4 credentials. When set, outbound requests are signed with AWS SigV4.
    sigv4: "AwsSigV4Credentials | None" = _Field(
        default=None,
        description="AWS SigV4 credentials. When set, outbound requests are signed with AWS SigV4.",
    )


class AwsSigV4Credentials(_ProtoModel):
    """
    AwsSigV4Credentials holds the credentials needed to sign requests with AWS SigV4.
    """

    access_key_id: str = _Field(default="")
    secret_access_key: str = _Field(default="")
    region: str = _Field(default="")
    service_name: str = _Field(default="")
    session_token: str = _Field(default="")


class AWSAccessKey(_ProtoModel):
    """
    AWSAccessKey is a long-term credential used to authenticate AWS requests.
    """

    access_key_id: str = _Field(default="")
    secret_access_key: str = _Field(default="")


class AwsRole(_ProtoModel):
    """
    AwsRole represents a single AWS IAM role that can be assumed.
    """

    # The ARN of the IAM role to assume
    assume_role_arn: str = _Field(
        default="",
        description="The ARN of the IAM role to assume",
    )
    # External ID for AWS STS AssumeRole for enhanced security and AWS compliance.
    # Optional: Used when the role's trust policy requires it.
    external_id: str = _Field(
        default="",
        description="External ID for AWS STS AssumeRole for enhanced security and AWS compliance.\nOptional: Used when the role's trust policy requires it.",
    )


class AwsRoleChain(_ProtoModel):
    """
    AwsRoleChain represents an ordered sequence of roles to assume.
    Each role in the chain assumes the next using the previous role's temporary credentials.
    This enables cross-account access patterns like hub-and-spoke architectures.

    Example: [HubRole, SpokeRole] creates the chain:
    Base credentials → HubRole → SpokeRole → Bedrock API
    """

    # Ordered list of roles to assume in sequence.
    roles: "list[AwsRole]" = _Field(
        default_factory=list,
        description="Ordered list of roles to assume in sequence.",
    )


class BedrockConnectionSpec(_ProtoModel):
    """
    BedrockConnectionSpec defines the information needed to make and parse a request to AWS Bedrock.
    """

    # Specifies the model id to use (Bedrock Converse API).
    model_id: str | None = _Field(
        default=None,
        description='Specifies the model id to use (Bedrock Converse API).\nOnly one of the fields can be specified with: ["model_id", "agent_runtime_arn"] (oneof target)',
    )
    # AgentCore runtime ARN. When set, validation invokes an AgentCore agent
    # via InvokeAgentRuntime instead of a Bedrock model via Converse.
    agent_runtime_arn: str | None = _Field(
        default=None,
        description='AgentCore runtime ARN. When set, validation invokes an AgentCore agent\nvia InvokeAgentRuntime instead of a Bedrock model via Converse.\nOnly one of the fields can be specified with: ["model_id", "agent_runtime_arn"] (oneof target)',
    )
    # A json path specifying where in the response json payload we can find the LLM's response response string. Note that
    # the path must point to a string value in the json payload. Whitespace and other special characters can be encoded
    # as unicode (\u0020). Periods in json fields can be escaped with a backslash.
    response_json_path: str = _Field(
        default="",
        description="A json path specifying where in the response json payload we can find the LLM's response response string. Note that\nthe path must point to a string value in the json payload. Whitespace and other special characters can be encoded\nas unicode (\\u0020). Periods in json fields can be escaped with a backslash.",
    )
    # The body template which is sent to the model after updating by replacing {{prompt}} with different prompt attacks
    # within the struct. Only one {{prompt}} is currently supported.
    body_template: dict[str, _Any] | None = _Field(
        default=None,
        description="The body template which is sent to the model after updating by replacing {{prompt}} with different prompt attacks\nwithin the struct. Only one {{prompt}} is currently supported.",
    )
    # The role we should assume to access the bedrock model
    assume_role_arn: str | None = _Field(
        default=None,
        description='The role we should assume to access the bedrock model\nOnly one of the fields can be specified with: ["assume_role_arn", "aws_access_key", "aws_role_chain"] (oneof auth_spec)',
    )
    # The aws access key to access the bedrock model
    aws_access_key: "AWSAccessKey | None" = _Field(
        default=None,
        description='The aws access key to access the bedrock model\nOnly one of the fields can be specified with: ["assume_role_arn", "aws_access_key", "aws_role_chain"] (oneof auth_spec)',
    )
    # Ordered sequence of AWS roles to assume for cross-account access.
    # Each role assumes the next in sequence using the previous role's temporary credentials.
    # The final role in the chain must have permissions to invoke Bedrock APIs.
    aws_role_chain: "AwsRoleChain | None" = _Field(
        default=None,
        description="Ordered sequence of AWS roles to assume for cross-account access.\nEach role assumes the next in sequence using the previous role's temporary credentials.\nThe final role in the chain must have permissions to invoke Bedrock APIs.\nOnly one of the fields can be specified with: [\"assume_role_arn\", \"aws_access_key\", \"aws_role_chain\"] (oneof auth_spec)",
    )
    # The standard text based model configuration containing max_tokens, temperature,
    # top_p and stop_sequences parameters for converse API calls.
    inference_config: "BedrockInferenceConfig | None" = _Field(
        default=None,
        description="The standard text based model configuration containing max_tokens, temperature,\ntop_p and stop_sequences parameters for converse API calls.",
    )
    # The additional configuration parameters associated with the model
    additional_config: dict[str, _Any] | None = _Field(
        default=None,
        description="The additional configuration parameters associated with the model",
    )
    # The AWS region code to use for Bedrock.
    region: "AWSRegion | None" = _Field(
        default=None,
        description="The AWS region code to use for Bedrock.",
    )
    # External ID for AWS STS AssumeRole for enhanced security and AWS compliance.
    # Optional: Used when assume_role_arn is specified and customer has configured it.
    external_id: str = _Field(
        default="",
        description="External ID for AWS STS AssumeRole for enhanced security and AWS compliance.\nOptional: Used when assume_role_arn is specified and customer has configured it.",
    )

    @_model_validator(mode="after")
    def _validate_oneof_target(self) -> "BedrockConnectionSpec":
        _set = [
            f for f in ("model_id", "agent_runtime_arn") if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(f"oneof 'target': only one field may be set, got {_set!r}")
        return self
    @_model_validator(mode="after")
    def _validate_oneof_auth_spec(self) -> "BedrockConnectionSpec":
        _set = [
            f
            for f in ("assume_role_arn", "aws_access_key", "aws_role_chain")
            if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'auth_spec': only one field may be set, got {_set!r}"
            )
        return self


class BedrockInferenceConfig(_ProtoModel):
    # The maximum number of tokens to allow in the generated response
    max_tokens: int = _Field(
        default=0,
        description="The maximum number of tokens to allow in the generated response",
    )
    # The likelihood of the model selecting higher-probability options while generating a response
    temperature: float = _Field(
        default=0.0,
        description="The likelihood of the model selecting higher-probability options while generating a response",
    )
    # The percentage of most-likely candidates that the model considers for the next token
    top_p: float = _Field(
        default=0.0,
        description="The percentage of most-likely candidates that the model considers for the next token",
    )
    # A list of stop sequences that causes the model to stop generating the response.
    stop_sequences: list[str] = _Field(
        default_factory=list,
        description="A list of stop sequences that causes the model to stop generating the response.",
    )


class ModelConnectionSpec(_ProtoModel):
    http: "HttpConnectionSpec | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["http", "bedrock", "websocket"] (oneof spec)',
    )
    bedrock: "BedrockConnectionSpec | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["http", "bedrock", "websocket"] (oneof spec)',
    )
    websocket: "WebsocketConnectionSpec | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["http", "bedrock", "websocket"] (oneof spec)',
    )
    # When true, model output is treated as sensitive: it will not be saved to
    # the database, logged in plaintext, etc.
    model_output_is_sensitive: bool = _Field(
        default=False,
        description="When true, model output is treated as sensitive: it will not be saved to\nthe database, logged in plaintext, etc.",
    )
    # HTTP status codes that mean the request was blocked (treated as defended, not skipped). HTTP targets only.
    block_status_codes: list[int] = _Field(
        default_factory=list,
        description="HTTP status codes that mean the request was blocked (treated as defended, not skipped). HTTP targets only.",
    )
    # JSON path checked for a block signal when the output path yields nothing; a present, non-empty value means blocked. Applies to any connection type that parses a JSON response.
    block_response_key: str = _Field(
        default="",
        description="JSON path checked for a block signal when the output path yields nothing; a present, non-empty value means blocked. Applies to any connection type that parses a JSON response.",
    )

    @_model_validator(mode="after")
    def _validate_oneof_spec(self) -> "ModelConnectionSpec":
        _set = [
            f for f in ("http", "bedrock", "websocket") if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(f"oneof 'spec': only one field may be set, got {_set!r}")
        return self


class TestModelConnectionRequest(_ProtoModel):
    """
    Request to test model connectivity.
    """

    model_connection: "ModelConnectionSpec | None" = _Field(default=None)
    multi_turn_enabled: bool = _Field(default=False)


class TestModelConnectionResponse(_ProtoModel):
    """
    Response from model connectivity test.
    """

    success: bool = _Field(default=False)
    latency_ms: ProtoInt64 = _Field(default=0)
    error_message: str | None = _Field(default=None)


class RedTeamReport(_ProtoModel):
    """
    RedTeamReport is the comprehensive report for a completed red team job.
    """

    schema_version: str = _Field(default="")
    generated_at: ProtoTimestamp | None = _Field(default=None)
    scan_info: "RedTeamScanInfo | None" = _Field(default=None)
    run_ids: list[str] = _Field(
        default_factory=list,
    )
    findings: "list[RedTeamFinding]" = _Field(
        default_factory=list,
    )
    known_gaps: "list[RedTeamKnownGap]" = _Field(
        default_factory=list,
    )


class RedTeamScanInfo(_ProtoModel):
    """
    Scan-level context and aggregate counts.
    """

    scan_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goals: list[str] = _Field(
        default_factory=list,
    )
    total_attacks: int = _Field(default=0)
    successful_attacks: int = _Field(default=0)
    failed_attacks: int = _Field(default=0)
    error_attacks: int = _Field(default=0)


class RedTeamKnownGap(_ProtoModel):
    gap_id: str = _Field(default="")
    notes: str = _Field(default="")


class RedTeamFinding(_ProtoModel):
    """
    One finding per adaptive red team run.
    """

    finding_id: str = _Field(default="")
    success: bool = _Field(default=False)
    goal: str = _Field(default="")
    run_id: str = _Field(default="")
    attack_success: "RedTeamAttackSuccess | None" = _Field(default=None)
    attempt: "RedTeamAttempt | None" = _Field(default=None)
    evidence_chain: "RedTeamEvidenceChain | None" = _Field(default=None)
    findings_summary: "RedTeamFindingsSummary | None" = _Field(default=None)
    timelines: "list[RedTeamTimelineEvent]" = _Field(
        default_factory=list,
    )


class RedTeamAttackSuccess(_ProtoModel):
    """
    Score-based success determination from the attack judge.
    """

    succeeded: bool = _Field(default=False)
    score: int = _Field(default=0)
    source: str = _Field(default="")
    success_threshold: int = _Field(default=0)
    evidence: dict[str, _Any] | None = _Field(default=None)


class RedTeamAttempt(_ProtoModel):
    """
    The winning (or best) attempt from the attack phase.
    """

    attempt_index: int = _Field(default=0)
    total_attempts: int = _Field(default=0)
    sample_id: str = _Field(default="")
    conversations: "list[RedTeamConversationGroup]" = _Field(
        default_factory=list,
    )
    request_refs: "list[RedTeamRequestRef]" = _Field(
        default_factory=list,
    )
    transcript_excerpt: "RedTeamTranscriptExcerpt | None" = _Field(default=None)


class RedTeamConversationGroup(_ProtoModel):
    """
    A group of messages for one direction (target_request or target_response).
    """

    kind: str = _Field(default="")
    messages: "list[RedTeamChatMessage]" = _Field(
        default_factory=list,
    )


class RedTeamChatMessage(_ProtoModel):
    role: str = _Field(default="")
    content: str = _Field(default="")


class RedTeamRequestRef(_ProtoModel):
    kind: str = _Field(default="")
    request_id: str = _Field(default="")


class RedTeamTranscriptExcerpt(_ProtoModel):
    """
    Key request/response pair for the winning attempt.
    """

    target_request: "RedTeamTranscriptMessage | None" = _Field(default=None)
    target_response: "RedTeamTranscriptMessage | None" = _Field(default=None)


class RedTeamTranscriptMessage(_ProtoModel):
    messages: "list[RedTeamChatMessage]" = _Field(
        default_factory=list,
    )
    content: str = _Field(default="")


class RedTeamEvidenceChain(_ProtoModel):
    """
    Phase-level artifact references.
    """

    plan: dict[str, _Any] | None = _Field(default=None)
    context: dict[str, _Any] | None = _Field(default=None)
    ideation: dict[str, _Any] | None = _Field(default=None)
    generation: dict[str, _Any] | None = _Field(default=None)
    transcript: dict[str, _Any] | None = _Field(default=None)


class RedTeamFindingsSummary(_ProtoModel):
    """
    Aggregated judgment findings for a run.
    """

    finding_count: int = _Field(default=0)
    status: str = _Field(default="")
    guardrails_summary: "RedTeamGuardrailsSummary | None" = _Field(default=None)
    findings: "list[RedTeamFindingDetail]" = _Field(
        default_factory=list,
    )
    reason: str = _Field(default="")
    summary: str = _Field(default="")
    limitations: list[str] = _Field(
        default_factory=list,
    )
    reference_meta: dict[str, _Any] | None = _Field(default=None)


class RedTeamGuardrailsSummary(_ProtoModel):
    attack_technique_counts: dict[str, int] = _Field(
        default_factory=dict,
    )
    blocked_attack_technique_counts: dict[str, int] = _Field(
        default_factory=dict,
    )
    blocked_attempt_count: int = _Field(default=0)
    success_attempt_count: int = _Field(default=0)
    success_attack_technique_counts: dict[str, int] = _Field(
        default_factory=dict,
    )
    layer_catalogs: "list[RedTeamGuardrailLayer]" = _Field(
        default_factory=list,
    )
    config_present: bool = _Field(default=False)
    notes: list[str] = _Field(
        default_factory=list,
    )


class RedTeamGuardrailLayer(_ProtoModel):
    layer_id: str = _Field(default="")
    layer_name: str = _Field(default="")


class RedTeamFindingDetail(_ProtoModel):
    """
    A single structured finding from the judgment agent.
    """

    finding_id: str = _Field(default="")
    title: str = _Field(default="")
    confidence: float = _Field(default=0.0)
    confidence_level: str = _Field(default="")
    primary_failure: "RedTeamClaim | None" = _Field(default=None)
    contributing_factors: "list[RedTeamContributingFactor]" = _Field(
        default_factory=list,
    )
    enabling_conditions: "list[RedTeamClaim]" = _Field(
        default_factory=list,
    )
    control_gaps: "list[RedTeamClaim]" = _Field(
        default_factory=list,
    )
    remediations: "list[RedTeamRemediation]" = _Field(
        default_factory=list,
    )
    taxonomy_mappings: "list[RedTeamTaxonomyMapping]" = _Field(
        default_factory=list,
    )
    proof: "RedTeamProof | None" = _Field(default=None)
    reproduction: "RedTeamReproduction | None" = _Field(default=None)
    limitations: list[str] = _Field(
        default_factory=list,
    )


class RedTeamClaim(_ProtoModel):
    """
    Structured claim used in primary_failure, enabling_conditions, control_gaps.
    """

    claim_type: str = _Field(default="")
    confidence_level: str = _Field(default="")
    confidence_rationale: str = _Field(default="")
    confidence_score: float = _Field(default=0.0)
    evidence_basis: str = _Field(default="")
    statement: str = _Field(default="")
    control_attribution: "RedTeamControlAttribution | None" = _Field(default=None)


class RedTeamControlAttribution(_ProtoModel):
    guardrail_ids: list[str] = _Field(
        default_factory=list,
    )
    layer_id: str = _Field(default="")
    sources: list[str] = _Field(
        default_factory=list,
    )
    status: str = _Field(default="")


class RedTeamContributingFactor(_ProtoModel):
    claim: str = _Field(default="")
    confidence: float = _Field(default=0.0)
    caveat: str = _Field(default="")


class RedTeamRemediation(_ProtoModel):
    recommendation: str = _Field(default="")
    controls: "list[RedTeamControlMapping]" = _Field(
        default_factory=list,
    )
    implementation_example: "RedTeamImplementationExample | None" = _Field(default=None)
    scope: str = _Field(default="")
    priority: str = _Field(default="")


class RedTeamControlMapping(_ProtoModel):
    framework_id: str = _Field(default="")
    control_id: str = _Field(default="")
    control_name: str = _Field(default="")
    confidence: float = _Field(default=0.0)
    rationale: str = _Field(default="")


class RedTeamImplementationExample(_ProtoModel):
    system_prompt_addendum: str = _Field(default="")
    post_processing_pseudocode: str = _Field(default="")
    regression_test_sketch: str = _Field(default="")


class RedTeamTaxonomyMapping(_ProtoModel):
    taxonomy_id: str = _Field(default="")
    technique_id: str = _Field(default="")
    technique_name: str = _Field(default="")
    objective_id: str = _Field(default="")
    objective_name: str = _Field(default="")
    subtechnique_ids: list[str] = _Field(
        default_factory=list,
    )
    standards_mappings: list[str] = _Field(
        default_factory=list,
    )
    confidence: float = _Field(default=0.0)
    rationale: str = _Field(default="")


class RedTeamProof(_ProtoModel):
    excerpt: str = _Field(default="")
    excerpt_hash: str = _Field(default="")
    excerpt_meta: dict[str, _Any] | None = _Field(default=None)


class RedTeamReproduction(_ProtoModel):
    prompt: str = _Field(default="")
    expected_http_status: int = _Field(default=0)
    provenance: str = _Field(default="")
    expected_markers: list[str] = _Field(
        default_factory=list,
    )


class RedTeamTimelineEvent(_ProtoModel):
    kind: str = _Field(default="")
    label: str = _Field(default="")
    phase: str = _Field(default="")
    t: ProtoTimestamp | None = _Field(default=None)
    details: dict[str, _Any] | None = _Field(default=None)


class RedTeamTargetContext(_ProtoModel):
    """
    Reusable target-context payload for red-team/adaptive testing. Describes the
    target application so attacks can be tailored to its architecture, defenses,
    data surfaces, and compliance posture.
    """

    class Environment(_ProtoEnum):
        """
        Deployment environment the target runs in.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        DEVELOPMENT = ("DEVELOPMENT", 1)
        TEST = ("TEST", 2)
        STAGING = ("STAGING", 3)
        PRODUCTION = ("PRODUCTION", 4)
        SANDBOX = ("SANDBOX", 5)
        OTHER = ("OTHER", 99)

    class ArchitectureType(_ProtoEnum):
        """
        Architectural pattern(s) the target implements.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        SINGLE_AGENT = ("SINGLE_AGENT", 1)
        MULTI_AGENT = ("MULTI_AGENT", 2)
        RAG = ("RAG", 3)
        TOOL_USING_AGENT = ("TOOL_USING_AGENT", 4)
        WORKFLOW_ORCHESTRATION = ("WORKFLOW_ORCHESTRATION", 5)
        CHATBOT = ("CHATBOT", 6)
        OTHER = ("OTHER", 99)

    class LLMProvider(_ProtoEnum):
        """
        Vendor of the underlying large language model.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        OPENAI = ("OPENAI", 1)
        AZURE_OPENAI = ("AZURE_OPENAI", 2)
        ANTHROPIC = ("ANTHROPIC", 3)
        GOOGLE = ("GOOGLE", 4)
        AWS_BEDROCK = ("AWS_BEDROCK", 5)
        META = ("META", 6)
        CISCO = ("CISCO", 7)
        OTHER = ("OTHER", 99)

    class ToolRiskLevel(_ProtoEnum):
        """
        Potential impact if a tool is misused, from low to critical.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        LOW_READ_ONLY_NO_PII = ("LOW_READ_ONLY_NO_PII", 1)
        MEDIUM_READ_ONLY_WITH_PII = ("MEDIUM_READ_ONLY_WITH_PII", 2)
        HIGH_MUTATES_DATA = ("HIGH_MUTATES_DATA", 3)
        CRITICAL_PRIVILEGED_OR_EXTERNAL = ("CRITICAL_PRIVILEGED_OR_EXTERNAL", 4)

    class ToolAccessType(_ProtoEnum):
        """
        Whether a tool reads, mutates data, and/or reaches external systems.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        READ_ONLY = ("READ_ONLY", 1)
        MUTATES_INTERNAL_DATA = ("MUTATES_INTERNAL_DATA", 2)
        EXTERNAL_ACCESS = ("EXTERNAL_ACCESS", 3)
        MUTATES_AND_EXTERNAL_ACCESS = ("MUTATES_AND_EXTERNAL_ACCESS", 4)

    class DefenseType(_ProtoEnum):
        """
        Standard categories of protective controls deployed around the target.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        INPUT_FILTERS = ("INPUT_FILTERS", 1)
        OUTPUT_FILTERS = ("OUTPUT_FILTERS", 2)
        PROMPT_INJECTION_DETECTION = ("PROMPT_INJECTION_DETECTION", 3)
        PII_DETECTION = ("PII_DETECTION", 4)
        RATE_LIMITING = ("RATE_LIMITING", 5)
        CISCO_AI_FIREWALL_GUARDRAILS = ("CISCO_AI_FIREWALL_GUARDRAILS", 6)
        AWS_BEDROCK_GUARDRAILS = ("AWS_BEDROCK_GUARDRAILS", 7)
        AZURE_CONTENT_SAFETY = ("AZURE_CONTENT_SAFETY", 8)
        OPENAI_MODERATION_API = ("OPENAI_MODERATION_API", 9)
        CUSTOM_GUARDRAILS = ("CUSTOM_GUARDRAILS", 10)

    class RagAccessControl(_ProtoEnum):
        """
        Access-control model applied to data the target retrieves.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        NONE = ("NONE", 1)
        PUBLIC = ("PUBLIC", 2)
        USER_SCOPED = ("USER_SCOPED", 3)
        ROLE_SCOPED = ("ROLE_SCOPED", 4)
        TENANT_SCOPED = ("TENANT_SCOPED", 5)
        SERVICE_ACCOUNT = ("SERVICE_ACCOUNT", 6)
        CUSTOM = ("CUSTOM", 99)

    class MemoryScope(_ProtoEnum):
        """
        Persistence/isolation scope of the target's memory.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        NONE = ("NONE", 1)
        SESSION = ("SESSION", 2)
        USER = ("USER", 3)
        TENANT = ("TENANT", 4)
        GLOBAL = ("GLOBAL", 5)
        CUSTOM = ("CUSTOM", 99)

    class ComplianceRequirement(_ProtoEnum):
        """
        Regulatory framework the target must comply with.
        """

        UNSPECIFIED = ("UNSPECIFIED", 0)
        HIPAA = ("HIPAA", 1)
        SOC_2 = ("SOC_2", 2)
        FERPA = ("FERPA", 3)
        NIST_AI_RMF = ("NIST_AI_RMF", 4)
        GDPR = ("GDPR", 5)
        PCI_DSS = ("PCI_DSS", 6)
        EU_AI_ACT = ("EU_AI_ACT", 7)

    class ArchitecturePurpose(_ProtoModel):
        """
        Describes what the target is, where it runs, and how it is built.
        """

        # Free-form summary of the application's purpose and behavior.
        app_description: str = _Field(
            default="",
            description="Free-form summary of the application's purpose and behavior.",
        )
        # Deployment environment (development, production, sandbox, etc.).
        environment: "RedTeamTargetContext.Environment | None" = _Field(
            default=None,
            description="Deployment environment (development, production, sandbox, etc.).",
        )
        # Architectural patterns the target uses (may be more than one).
        architecture_types: "list[RedTeamTargetContext.ArchitectureType]" = _Field(
            default_factory=list,
            description="Architectural patterns the target uses (may be more than one).",
        )
        # Vendor providing the underlying LLM.
        llm_provider: "RedTeamTargetContext.LLMProvider | None" = _Field(
            default=None,
            description="Vendor providing the underlying LLM.",
        )
        # Specific model name and whether/how it has been fine-tuned.
        model_and_fine_tune_status: str = _Field(
            default="",
            description="Specific model name and whether/how it has been fine-tuned.",
        )

    class SystemPrompt(_ProtoModel):
        """
        A system/developer prompt attributed to a specific agent in the target.
        """

        # Identifier of the agent this prompt governs (empty for single-agent apps).
        agent_name: str = _Field(
            default="",
            description="Identifier of the agent this prompt governs (empty for single-agent apps).",
        )
        # The system prompt text itself.
        # System prompts contain XML-like structural tags (<policy>, <task>,
        # etc.) used for prompt engineering; exempt from HTML sanitization so the
        # sanitizer does not strip them before red-team/adaptive testing.
        prompt: str = _Field(
            default="",
            description="The system prompt text itself.\nSystem prompts contain XML-like structural tags (<policy>, <task>,\netc.) used for prompt engineering; exempt from HTML sanitization so the\nsanitizer does not strip them before red-team/adaptive testing.",
        )

    class Tool(_ProtoModel):
        """
        A tool/function the target agent can call, and its risk profile.
        """

        # Tool name as exposed to the model.
        name: str = _Field(
            default="",
            description="Tool name as exposed to the model.",
        )
        # Human-readable description of what the tool does.
        description: str = _Field(
            default="",
            description="Human-readable description of what the tool does.",
        )
        # Potential impact level if the tool is misused.
        risk_level: "RedTeamTargetContext.ToolRiskLevel | None" = _Field(
            default=None,
            description="Potential impact level if the tool is misused.",
        )
        # Whether the tool reads, mutates, and/or reaches external systems.
        access_type: "RedTeamTargetContext.ToolAccessType | None" = _Field(
            default=None,
            description="Whether the tool reads, mutates, and/or reaches external systems.",
        )
        # Scope of permissions granted to the tool (e.g. roles, data boundaries).
        permission_scope: str = _Field(
            default="",
            description="Scope of permissions granted to the tool (e.g. roles, data boundaries).",
        )
        # OpenAPI/JSON schema of the tool's parameters, serialized as a string.
        parameters_openapi_schema: str = _Field(
            default="",
            description="OpenAPI/JSON schema of the tool's parameters, serialized as a string.",
        )

    class DefensesDeployed(_ProtoModel):
        """
        Protective controls deployed around the target.
        """

        # Standard defense categories that are enabled.
        enabled_defenses: "list[RedTeamTargetContext.DefenseType]" = _Field(
            default_factory=list,
            description="Standard defense categories that are enabled.",
        )
        # Description of any custom defenses not covered by DefenseType.
        other_custom_defenses: str = _Field(
            default="",
            description="Description of any custom defenses not covered by DefenseType.",
        )

    class DataRagMemory(_ProtoModel):
        """
        Retrieval, data-source, and memory characteristics of the target.
        """

        # Identifiers or descriptions of data sources the target retrieves from.
        rag_sources: list[str] = _Field(
            default_factory=list,
            description="Identifiers or descriptions of data sources the target retrieves from.",
        )
        # Access-control model applied to retrieved data.
        rag_access_control: "RedTeamTargetContext.RagAccessControl | None" = _Field(
            default=None,
            description="Access-control model applied to retrieved data.",
        )
        # Persistence/isolation scope of the target's memory.
        memory_scope: "RedTeamTargetContext.MemoryScope | None" = _Field(
            default=None,
            description="Persistence/isolation scope of the target's memory.",
        )

    class ComplianceLimitationsNotes(_ProtoModel):
        """
        Compliance obligations, known weaknesses, and operator notes.
        """

        # Regulatory frameworks the target must comply with.
        compliance_requirements: "list[RedTeamTargetContext.ComplianceRequirement]" = _Field(
            default_factory=list,
            description="Regulatory frameworks the target must comply with.",
        )
        # Known functional or safety limitations of the target.
        known_limitations: list[str] = _Field(
            default_factory=list,
            description="Known functional or safety limitations of the target.",
        )
        # Previously discovered security issues relevant to testing.
        prior_security_issues: list[str] = _Field(
            default_factory=list,
            description="Previously discovered security issues relevant to testing.",
        )
        # Link to external documentation about the target.
        documentation_url: str = _Field(
            default="",
            description="Link to external documentation about the target.",
        )
        # Free-form notes for the red-team operator.
        notes: str = _Field(
            default="",
            description="Free-form notes for the red-team operator.",
        )

    class GuardrailAttribution(_ProtoModel):
        """
        A named guardrail and the token patterns it enforces.
        """

        # Name/identifier of the guardrail.
        guardrail_name: str = _Field(
            default="",
            description="Name/identifier of the guardrail.",
        )
        # Literal or regex patterns the guardrail matches on.
        # Patterns carry literal/regex guardrail tokens (e.g. <script>,
        # prompt-boundary markers) that must be preserved byte-for-byte; exempt
        # from HTML sanitization so the engine tests against the real patterns.
        patterns: list[str] = _Field(
            default_factory=list,
            description="Literal or regex patterns the guardrail matches on.\nPatterns carry literal/regex guardrail tokens (e.g. <script>,\nprompt-boundary markers) that must be preserved byte-for-byte; exempt\nfrom HTML sanitization so the engine tests against the real patterns.",
        )

    # High-level description of the target: what it is, where it runs, and which
    # model powers it.
    architecture_purpose: "RedTeamTargetContext.ArchitecturePurpose | None" = _Field(
        default=None,
        description="High-level description of the target: what it is, where it runs, and which\nmodel powers it.",
    )
    # System/developer prompts governing the target, one entry per agent.
    system_prompts: "list[RedTeamTargetContext.SystemPrompt]" = _Field(
        default_factory=list,
        description="System/developer prompts governing the target, one entry per agent.",
    )
    # Tools/functions the target can invoke, with their risk and access profile.
    tools: "list[RedTeamTargetContext.Tool]" = _Field(
        default_factory=list,
        description="Tools/functions the target can invoke, with their risk and access profile.",
    )
    # Protective controls (filters, guardrails, moderation) deployed in front of
    # or around the target.
    defenses_deployed: "RedTeamTargetContext.DefensesDeployed | None" = _Field(
        default=None,
        description="Protective controls (filters, guardrails, moderation) deployed in front of\nor around the target.",
    )
    # Retrieval (RAG), data-source, and memory characteristics of the target.
    data_rag_memory: "RedTeamTargetContext.DataRagMemory | None" = _Field(
        default=None,
        description="Retrieval (RAG), data-source, and memory characteristics of the target.",
    )
    # Regulatory requirements, known limitations, and free-form operator notes.
    compliance_limitations_notes: "RedTeamTargetContext.ComplianceLimitationsNotes | None" = _Field(
        default=None,
        description="Regulatory requirements, known limitations, and free-form operator notes.",
    )
    # Named guardrails and the literal/regex token patterns they enforce.
    guardrail_attributions: "list[RedTeamTargetContext.GuardrailAttribution]" = _Field(
        default_factory=list,
        description="Named guardrails and the literal/regex token patterns they enforce.",
    )
