# DO NOT EDIT. Generated by protoc-gen-pydantic.

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)

from ._proto_types import ProtoTimestamp, ProtoUInt64, _EnumValueOptions, _ProtoEnum

from .common_pydantic import PageRequest

from .common_pydantic import PageInfo

from .common_pydantic import AttackRerunFilter

from aidefense.pydantic.validation.ai_validation_service.v1.ai_validation_service_pydantic import RedTeamTestRequest

from aidefense.pydantic.validation.ai_validation_service.v1.ai_validation_service_pydantic import RedTeamReport


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class AdaptiveRedTeamJobControlCommand(_ProtoEnum):
    """
    AdaptiveRedTeamJobControlCommand identifies the durable control operation
    delivered to the job workflow and forwarded to its active goal workflows.
    """

    ADAPTIVE_RED_TEAM_JOB_CONTROL_COMMAND_UNSPECIFIED = ("ADAPTIVE_RED_TEAM_JOB_CONTROL_COMMAND_UNSPECIFIED", 0)
    ADAPTIVE_RED_TEAM_JOB_CONTROL_COMMAND_PAUSE = ("ADAPTIVE_RED_TEAM_JOB_CONTROL_COMMAND_PAUSE", 1)
    ADAPTIVE_RED_TEAM_JOB_CONTROL_COMMAND_RESUME = ("ADAPTIVE_RED_TEAM_JOB_CONTROL_COMMAND_RESUME", 2)


class AdaptiveRedTeamActivityFailureDisposition(_ProtoEnum):
    """
    AdaptiveRedTeamActivityFailureDisposition tells the workflow whether an
    activity failure can be resumed after the underlying problem is corrected.
    """

    ADAPTIVE_RED_TEAM_ACTIVITY_FAILURE_DISPOSITION_UNSPECIFIED = ("ADAPTIVE_RED_TEAM_ACTIVITY_FAILURE_DISPOSITION_UNSPECIFIED", 0)
    # STOPPED represents a system-initiated, recoverable condition. The workflow
    # remains open and waits for an explicit resume command.
    ADAPTIVE_RED_TEAM_ACTIVITY_FAILURE_DISPOSITION_STOPPED = ("ADAPTIVE_RED_TEAM_ACTIVITY_FAILURE_DISPOSITION_STOPPED", 1)
    # FAILED represents an unrecoverable condition. The workflow terminates.
    ADAPTIVE_RED_TEAM_ACTIVITY_FAILURE_DISPOSITION_FAILED = ("ADAPTIVE_RED_TEAM_ACTIVITY_FAILURE_DISPOSITION_FAILED", 2)


class RedTeamJobSortField(_ProtoEnum):
    """
    Sortable fields for listing red team jobs.
    """

    RED_TEAM_JOB_SORT_FIELD_UNSPECIFIED = ("RED_TEAM_JOB_SORT_FIELD_UNSPECIFIED", 0)
    RED_TEAM_JOB_SORT_FIELD_CREATED_AT = ("RED_TEAM_JOB_SORT_FIELD_CREATED_AT", 1)
    RED_TEAM_JOB_SORT_FIELD_STATUS = ("RED_TEAM_JOB_SORT_FIELD_STATUS", 2)
    RED_TEAM_JOB_SORT_FIELD_STARTED_AT = ("RED_TEAM_JOB_SORT_FIELD_STARTED_AT", 3)
    RED_TEAM_JOB_SORT_FIELD_COMPLETED_AT = ("RED_TEAM_JOB_SORT_FIELD_COMPLETED_AT", 4)


class SortDirection(_ProtoEnum):
    """
    Sort direction for ordering results.
    """

    SORT_DIRECTION_UNSPECIFIED = ("SORT_DIRECTION_UNSPECIFIED", 0)
    SORT_DIRECTION_ASC = ("SORT_DIRECTION_ASC", 1)
    SORT_DIRECTION_DESC = ("SORT_DIRECTION_DESC", 2)


class RedTeamJobStatus(_ProtoEnum):
    """
    Job status for red team jobs.
    """

    RED_TEAM_JOB_STATUS_UNSPECIFIED = ("RED_TEAM_JOB_STATUS_UNSPECIFIED", 0)
    RED_TEAM_JOB_STATUS_CREATED = ("RED_TEAM_JOB_STATUS_CREATED", 1)
    RED_TEAM_JOB_STATUS_IN_PROGRESS = ("RED_TEAM_JOB_STATUS_IN_PROGRESS", 2)
    RED_TEAM_JOB_STATUS_COMPLETED = ("RED_TEAM_JOB_STATUS_COMPLETED", 3)
    RED_TEAM_JOB_STATUS_FAILED = ("RED_TEAM_JOB_STATUS_FAILED", 4)
    RED_TEAM_JOB_STATUS_PAUSED = (
        "RED_TEAM_JOB_STATUS_PAUSED",
        5,
        _EnumValueOptions(
            value_visibility=None,
        ),
    )
    RED_TEAM_JOB_STATUS_CANCELLED = (
        "RED_TEAM_JOB_STATUS_CANCELLED",
        6,
        _EnumValueOptions(
            value_visibility=None,
        ),
    )
    RED_TEAM_JOB_STATUS_STOPPED = (
        "RED_TEAM_JOB_STATUS_STOPPED",
        7,
        _EnumValueOptions(
            value_visibility=None,
        ),
    )


class Industry(_ProtoEnum):
    """
    Industry vertical used to bias red team attack generation.
    UNSPECIFIED falls back to INDUSTRY_DEFAULT on the data plane.
    """

    INDUSTRY_UNSPECIFIED = ("INDUSTRY_UNSPECIFIED", 0)
    INDUSTRY_DEFAULT = ("INDUSTRY_DEFAULT", 1)
    INDUSTRY_HEALTHCARE = ("INDUSTRY_HEALTHCARE", 2)
    INDUSTRY_FINANCIAL_SERVICES = ("INDUSTRY_FINANCIAL_SERVICES", 3)
    INDUSTRY_TECHNOLOGY = ("INDUSTRY_TECHNOLOGY", 4)
    INDUSTRY_RETAIL = ("INDUSTRY_RETAIL", 5)
    INDUSTRY_EDUCATION = ("INDUSTRY_EDUCATION", 6)
    INDUSTRY_GOVERNMENT = ("INDUSTRY_GOVERNMENT", 7)
    INDUSTRY_MANUFACTURING = ("INDUSTRY_MANUFACTURING", 8)
    INDUSTRY_ENERGY = ("INDUSTRY_ENERGY", 9)
    INDUSTRY_EQUIPMENT_RENTAL = ("INDUSTRY_EQUIPMENT_RENTAL", 10)
    INDUSTRY_HUMAN_CAPITAL_MANAGEMENT = ("INDUSTRY_HUMAN_CAPITAL_MANAGEMENT", 11)


class AdaptiveRedTeamJobActivityInput(_ProtoModel):
    """
    AdaptiveRedTeamJobActivityInput is the only payload retained in Temporal
    history for a GVS execution. goal_id is set when a goal child schedules
    goal-scoped work and remains empty for the compatible whole-job path. The
    payload contains only durable identifiers, never credentials, prompts,
    target configuration, or reports.
    """

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")


class GetAdaptiveRedTeamExecutionInputRequest(_ProtoModel):
    """
    GetAdaptiveRedTeamExecutionInputRequest identifies the Temporal activity
    asking CP to resolve fresh execution details.
    """

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")


class GetAdaptiveRedTeamExecutionInputResponse(_ProtoModel):
    """
    GetAdaptiveRedTeamExecutionInputResponse carries the sensitive, freshly
    resolved request directly from CP to GVS. It is not a Temporal payload.
    """

    request: "RedTeamTestRequest | None" = _Field(default=None)
    # CP-computed per-goal customer-model in-flight budget. This is returned
    # outside Temporal history with the freshly resolved execution request.
    model_max_inflight: int = _Field(
        default=0,
        description="CP-computed per-goal customer-model in-flight budget. This is returned\noutside Temporal history with the freshly resolved execution request.",
    )


class AdaptiveRedTeamActivityFailure(_ProtoModel):
    """
    AdaptiveRedTeamActivityFailure is carried as Temporal application-error
    detail by data-plane activities. Workflows must fail closed when the detail
    is absent or has an unspecified disposition.
    """

    disposition: "AdaptiveRedTeamActivityFailureDisposition | None" = _Field(
        default=None,
    )
    error_message: str = _Field(default="")


class AdaptiveRedTeamJobControlSignal(_ProtoModel):
    """
    AdaptiveRedTeamJobControlSignal is the Temporal pause/resume payload.
    """

    command: "AdaptiveRedTeamJobControlCommand | None" = _Field(default=None)


class AdaptiveRedTeamGoalWorkflowInput(_ProtoModel):
    """
    AdaptiveRedTeamGoalWorkflowInput identifies one goal execution owned by an
    adaptive red-team job. Only durable identifiers belong in Temporal history;
    workers resolve credentials, target configuration, and goal artifacts from
    the control plane when an activity executes. For each round, the goal
    workflow schedules GenerateConfig, ExecuteAttack, and PersistRoundResult in
    that order. Each activity starts only after the prior activity has persisted
    its output and returned the artifact identifier required by the next one.
    """

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")


class AdaptiveRedTeamGoalWorkflowResult(_ProtoModel):
    """
    AdaptiveRedTeamGoalWorkflowResult summarizes a successfully completed goal.
    The report itself remains in control-plane persistence and is referenced by
    its artifact identifier rather than copied into Temporal history.
    """

    goal_id: str = _Field(default="")
    completed_rounds: int = _Field(default=0)
    final_report_artifact_id: str = _Field(default="")


class AdaptiveRedTeamGenerateConfigActivityInput(_ProtoModel):
    """
    AdaptiveRedTeamGenerateConfigActivityInput identifies one logical
    configuration-generation operation. The activity derives its idempotency
    identity from the validated fields, in this exact segment order:
    adaptive-red-team:{tenant_id}:{job_id}:{goal_id}:round:{round}:generate-config.
    The identity is not accepted as an independent input, so it cannot disagree
    with the operation selectors. Temporal retries and pause/resume reuse the
    same identity; attempt numbers, Workflow Run IDs, timestamps, and random
    values are deliberately excluded.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")
    round_: int = _Field(
        default=0,
        alias="round",
    )


class AdaptiveRedTeamGenerateConfigActivityResult(_ProtoModel):
    """
    AdaptiveRedTeamGenerateConfigActivityResult references the generated
    configuration persisted by the activity before it reports completion.
    """

    config_artifact_id: str = _Field(default="")


class AdaptiveRedTeamExecuteAttackActivityInput(_ProtoModel):
    """
    AdaptiveRedTeamExecuteAttackActivityInput identifies one logical attack
    execution. It runs only after GenerateConfig returns config_artifact_id. The
    activity derives its idempotency identity from the validated fields, in this
    exact segment order:
    adaptive-red-team:{tenant_id}:{job_id}:{goal_id}:round:{round}:execute-attack.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")
    round_: int = _Field(
        default=0,
        alias="round",
    )
    config_artifact_id: str = _Field(default="")


class AdaptiveRedTeamExecuteAttackActivityResult(_ProtoModel):
    """
    AdaptiveRedTeamExecuteAttackActivityResult references the persisted result.
    continue_next_round is control metadata used by the deterministic goal
    workflow; the result payload itself remains outside Temporal history.
    """

    result_artifact_id: str = _Field(default="")
    continue_next_round: bool = _Field(default=False)


class AdaptiveRedTeamPersistRoundResultActivityInput(_ProtoModel):
    """
    AdaptiveRedTeamPersistRoundResultActivityInput projects one completed round
    into control-plane product state. It runs only after ExecuteAttack returns
    result_artifact_id. The activity derives its idempotency identity from the
    validated fields, in this exact segment order:
    adaptive-red-team:{tenant_id}:{job_id}:{goal_id}:round:{round}:persist-result.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")
    round_: int = _Field(
        default=0,
        alias="round",
    )
    result_artifact_id: str = _Field(default="")


class PauseRedTeamJobRequest(_ProtoModel):
    """
    PauseRedTeamJobRequest identifies a red team job to pause.
    """

    job_id: str = _Field(default="")


class PauseRedTeamJobResponse(_ProtoModel):
    """
    PauseRedTeamJobResponse is empty on success.
    """

    pass


class ResumeRedTeamJobRequest(_ProtoModel):
    """
    ResumeRedTeamJobRequest identifies a paused or stopped red team job to resume.
    """

    job_id: str = _Field(default="")


class ResumeRedTeamJobResponse(_ProtoModel):
    """
    ResumeRedTeamJobResponse is empty on success.
    """

    pass


class CancelRedTeamJobRequest(_ProtoModel):
    """
    CancelRedTeamJobRequest identifies a red team job to cancel.
    """

    job_id: str = _Field(default="")


class CancelRedTeamJobResponse(_ProtoModel):
    """
    CancelRedTeamJobResponse is empty on success.
    """

    pass


class RestartRedTeamJobRequest(_ProtoModel):
    """
    RestartRedTeamJobRequest identifies a cancelled red team job to restart as a
    new job.
    """

    # Unique identifier of the source job.
    job_id: str = _Field(
        default="",
        description="Unique identifier of the source job.",
    )
    options: "RestartRedTeamJobOptions | None" = _Field(default=None)


class RestartRedTeamJobResponse(_ProtoModel):
    """
    RestartRedTeamJobResponse identifies the new red team job.
    """

    job_id: str = _Field(default="")


class RedTeamJobSummary(_ProtoModel):
    """
    Summary of a red team job returned in list responses.
    """

    # Unique identifier for the red team job.
    job_id: str = _Field(
        default="",
        description="Unique identifier for the red team job.",
    )
    # Human-readable name supplied at job creation.
    name: str = _Field(
        default="",
        description="Human-readable name supplied at job creation.",
    )
    # Description supplied at job creation.
    description: str = _Field(
        default="",
        description="Description supplied at job creation.",
    )
    # Name of the target this job ran against (snapshot from the target at list time).
    target_name: str = _Field(
        default="",
        description="Name of the target this job ran against (snapshot from the target at list time).",
    )
    # Name of the validation profile this job used (snapshot from the profile at list time).
    profile_name: str = _Field(
        default="",
        description="Name of the validation profile this job used (snapshot from the profile at list time).",
    )
    # Current status of the red team job.
    status: "RedTeamJobStatus | None" = _Field(
        default=None,
        description="Current status of the red team job.",
    )
    # Populated only when status is FAILED.
    error_message: str | None = _Field(
        default=None,
        description="Populated only when status is FAILED.",
    )
    created_at: ProtoTimestamp | None = _Field(default=None)
    started_at: ProtoTimestamp | None = _Field(default=None)
    completed_at: ProtoTimestamp | None = _Field(default=None)
    # Industry vertical the job was run under.
    industry: "Industry | None" = _Field(
        default=None,
        description="Industry vertical the job was run under.",
    )
    # ID of the target this job ran against. Enables re-running (retry) the job.
    # Optional (unset) because the target may have been deleted since the job ran;
    # when present it must be a valid UUID.
    target_id: str | None = _Field(
        default=None,
        description="ID of the target this job ran against. Enables re-running (retry) the job.\nOptional (unset) because the target may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )
    # ID of the validation profile this job used. Enables re-running (retry) the job.
    # Optional (unset) because the profile may have been deleted since the job ran;
    # when present it must be a valid UUID.
    profile_id: str | None = _Field(
        default=None,
        description="ID of the validation profile this job used. Enables re-running (retry) the job.\nOptional (unset) because the profile may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )
    # recommended_goal_ids identify the target-recommended goals selected
    # for this run. When empty, no recommended goals are run.
    recommended_goal_ids: list[str] = _Field(
        default_factory=list,
        description="recommended_goal_ids identify the target-recommended goals selected\nfor this run. When empty, no recommended goals are run.",
    )


class ListRedTeamJobsRequest(_ProtoModel):
    """
    Request to list red team jobs with offset-based pagination, filtering, and sorting.
    """

    # Pagination input.
    page: "PageRequest | None" = _Field(
        default=None,
        description="Pagination input.",
    )
    # Field to sort by. Defaults to CREATED_AT.
    sort_field: "RedTeamJobSortField | None" = _Field(
        default=None,
        description="Field to sort by. Defaults to CREATED_AT.",
    )
    # Sort direction. Defaults to DESC.
    sort_direction: "SortDirection | None" = _Field(
        default=None,
        description="Sort direction. Defaults to DESC.",
    )
    # Filter by job status.
    status: "RedTeamJobStatus | None" = _Field(
        default=None,
        description="Filter by job status.",
    )
    # Return only jobs created at or after this timestamp.
    created_after: ProtoTimestamp | None = _Field(
        default=None,
        description="Return only jobs created at or after this timestamp.",
    )
    # Return only jobs created at or before this timestamp.
    created_before: ProtoTimestamp | None = _Field(
        default=None,
        description="Return only jobs created at or before this timestamp.",
    )
    # Pattern match across name, description, target name, profile name.
    search: str | None = _Field(
        default=None,
        description="Pattern match across name, description, target name, profile name.",
    )


class ListRedTeamJobsResponse(_ProtoModel):
    """
    Response for listing red team jobs.
    """

    jobs: "list[RedTeamJobSummary]" = _Field(
        default_factory=list,
    )
    # Pagination metadata.
    page_info: "PageInfo | None" = _Field(
        default=None,
        description="Pagination metadata.",
    )


class GetRedTeamJobRequest(_ProtoModel):
    """
    Request to get the full details of a red team job.
    """

    job_id: str = _Field(default="")


class GetRedTeamJobResponse(_ProtoModel):
    """
    Full details of a red team job.
    """

    # Unique identifier for the red team job.
    job_id: str = _Field(
        default="",
        description="Unique identifier for the red team job.",
    )
    # Human-readable name supplied at job creation.
    name: str = _Field(
        default="",
        description="Human-readable name supplied at job creation.",
    )
    # Description supplied at job creation.
    description: str = _Field(
        default="",
        description="Description supplied at job creation.",
    )
    # Name of the target this job ran against.
    target_name: str = _Field(
        default="",
        description="Name of the target this job ran against.",
    )
    # Name of the validation profile this job used.
    profile_name: str = _Field(
        default="",
        description="Name of the validation profile this job used.",
    )
    # Current status of the red team job.
    status: "RedTeamJobStatus | None" = _Field(
        default=None,
        description="Current status of the red team job.",
    )
    # Populated only when status is FAILED.
    error_message: str | None = _Field(
        default=None,
        description="Populated only when status is FAILED.",
    )
    created_at: ProtoTimestamp | None = _Field(default=None)
    started_at: ProtoTimestamp | None = _Field(default=None)
    completed_at: ProtoTimestamp | None = _Field(default=None)
    # Industry vertical the job was run under.
    industry: "Industry | None" = _Field(
        default=None,
        description="Industry vertical the job was run under.",
    )
    # ID of the target this job ran against. Enables re-running (retry) the job.
    # Optional (unset) because the target may have been deleted since the job ran;
    # when present it must be a valid UUID.
    target_id: str | None = _Field(
        default=None,
        description="ID of the target this job ran against. Enables re-running (retry) the job.\nOptional (unset) because the target may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )
    # ID of the validation profile this job used. Enables re-running (retry) the job.
    # Optional (unset) because the profile may have been deleted since the job ran;
    # when present it must be a valid UUID.
    profile_id: str | None = _Field(
        default=None,
        description="ID of the validation profile this job used. Enables re-running (retry) the job.\nOptional (unset) because the profile may have been deleted since the job ran;\nwhen present it must be a valid UUID.",
    )
    # recommended_goal_ids identify the target-recommended goals selected
    # for this run. When empty, no recommended goals are run.
    recommended_goal_ids: list[str] = _Field(
        default_factory=list,
        description="recommended_goal_ids identify the target-recommended goals selected\nfor this run. When empty, no recommended goals are run.",
    )


class RedTeamJobConfig(_ProtoModel):
    """
    RedTeamJobConfig contains the updatable fields for a red team job.
    Fields are optional so that validation rules only fire when a field is actually set.
    """

    # name is the human-readable name of the red team job
    name: str | None = _Field(
        default=None,
        description="name is the human-readable name of the red team job",
    )
    # description of the red team job
    description: str | None = _Field(
        default=None,
        description="description of the red team job",
    )


class UpdateRedTeamJobRequest(_ProtoModel):
    # job_id identifies which job to update (bound from URL path)
    job_id: str = _Field(
        default="",
        description="job_id identifies which job to update (bound from URL path)",
    )
    # Field mask specifies which fields in `job` to update.
    # If omitted or empty, grpc-gateway will auto-populate it from the JSON keys present in the request body.
    update_mask: list[str] | None = _Field(
        default=None,
        description="Field mask specifies which fields in `job` to update.\nIf omitted or empty, grpc-gateway will auto-populate it from the JSON keys present in the request body.",
    )
    # The red team job fields to update (HTTP body)
    job: "RedTeamJobConfig | None" = _Field(
        default=None,
        description="The red team job fields to update (HTTP body)",
    )


class UpdateRedTeamJobResponse(_ProtoModel):
    pass


class DeleteRedTeamJobRequest(_ProtoModel):
    """
    Request to soft-delete a red team job.
    """

    job_id: str = _Field(default="")


class DeleteRedTeamJobResponse(_ProtoModel):
    """
    Response for deleting a red team job. Empty on success.
    """

    pass


class StartRedTeamJobResponse(_ProtoModel):
    """
    Response for starting a red team test against an application. Contains the job ID of the started test.
    """

    job_id: str = _Field(default="")


class StartAdaptiveRedTeamRequest(_ProtoModel):
    """
    Request to start an adaptive red team test against any target type.
    Connection details are resolved from the target; test configuration from the profile.
    """

    # The ID of the target to test. All connection details are resolved server-side from this target.
    target_id: str = _Field(
        default="",
        description="The ID of the target to test. All connection details are resolved server-side from this target.",
    )
    # The ID of the validation profile to use. Test configuration (language,
    # content categories, custom goals, multi-turn) is resolved from this profile.
    profile_id: str = _Field(
        default="",
        description="The ID of the validation profile to use. Test configuration (language,\ncontent categories, custom goals, multi-turn) is resolved from this profile.",
    )
    # Human-readable name for this red team test run.
    name: str = _Field(
        default="",
        description="Human-readable name for this red team test run.",
    )
    # Optional description of this red team test run.
    description: str = _Field(
        default="",
        description="Optional description of this red team test run.",
    )
    # When true, model outputs will not be persisted or logged in plaintext.
    model_output_is_sensitive: bool | None = _Field(
        default=None,
        description="When true, model outputs will not be persisted or logged in plaintext.",
    )
    # Industry vertical to use when generating attacks. Optional.
    # When UNSPECIFIED, the data plane falls back to INDUSTRY_DEFAULT.
    industry: "Industry | None" = _Field(
        default=None,
        description="Industry vertical to use when generating attacks. Optional.\nWhen UNSPECIFIED, the data plane falls back to INDUSTRY_DEFAULT.",
    )
    # recommended_goal_ids identify the target-recommended goals selected
    # for this run. When empty, no recommended goals are run.
    recommended_goal_ids: list[str] = _Field(
        default_factory=list,
        description="recommended_goal_ids identify the target-recommended goals selected\nfor this run. When empty, no recommended goals are run.",
    )


class UpdateRedTeamJobStatusRequest(_ProtoModel):
    """
    Request to update red team job status. Internal callback from data plane.
    """

    job_id: str = _Field(default="")
    tenant_id: str = _Field(default="")
    status: "RedTeamJobStatus | None" = _Field(default=None)
    error_message: str = _Field(default="")
    # goal_id identifies which goal this status callback is for, when the control
    # plane dispatches one data-plane call per goal. Empty on the legacy path
    # where a single call carries all goals.
    goal_id: str = _Field(
        default="",
        description="goal_id identifies which goal this status callback is for, when the control\nplane dispatches one data-plane call per goal. Empty on the legacy path\nwhere a single call carries all goals.",
    )


class UpdateRedTeamJobStatusResponse(_ProtoModel):
    pass


class GetRedTeamReportRequest(_ProtoModel):
    """
    Request to get the comprehensive report for an adaptive red team job.
    """

    job_id: str = _Field(default="")


class GetRedTeamReportResponse(_ProtoModel):
    report: "RedTeamReport | None" = _Field(default=None)


class UpsertRedTeamReportRequest(_ProtoModel):
    """
    Request to create or update the comprehensive report for a red team job. Internal callback from dataplane.
    """

    job_id: str = _Field(default="")
    report: "RedTeamReport | None" = _Field(default=None)
    # goal_id identifies which goal this report is for, when the control plane
    # dispatches one data-plane call per goal. Empty on the legacy path where a
    # single call carries all goals.
    goal_id: str = _Field(
        default="",
        description="goal_id identifies which goal this report is for, when the control plane\ndispatches one data-plane call per goal. Empty on the legacy path where a\nsingle call carries all goals.",
    )


class UpsertRedTeamReportResponse(_ProtoModel):
    pass


class StoreGoalContextRequest(_ProtoModel):
    """
    StoreGoalContextRequest is one frame of the client-streamed snapshot upload.
    The first frame MUST carry `key`; every subsequent frame carries a `chunk`.
    Concatenating the chunk bytes in arrival order yields the raw JSON snapshot
    (the entire MemoryStore map for this job/goal). Framing keeps each message
    under the gRPC size limit even when the snapshot is large (~20 MB).
    """

    key: "GoalContextKey | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["key", "chunk"] (oneof frame)',
    )
    chunk: bytes | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["key", "chunk"] (oneof frame)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_frame(self) -> "StoreGoalContextRequest":
        _set = [f for f in ("key", "chunk") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'frame': only one field may be set, got {_set!r}")
        return self


class GoalContextKey(_ProtoModel):
    """
    GoalContextKey identifies the (job, goal) whose snapshot is being written.
    """

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")


class StoreGoalContextResponse(_ProtoModel):
    pass


class GetGoalContextRequest(_ProtoModel):
    """
    GetGoalContextRequest queries durable goal context for one job, optionally
    filtered to a single goal. tenant_id and job_id are required.
    """

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")


class GetGoalContextResponse(_ProtoModel):
    """
    GetGoalContextResponse is one frame of the server-streamed read. Each entry
    starts with a `header` frame, followed by one or more `chunk` frames;
    concatenating an entry's chunk bytes yields its raw JSON snapshot. A new
    `header` marks the start of the next entry.
    """

    header: "GoalContextEntryHeader | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["header", "chunk"] (oneof frame)',
    )
    chunk: bytes | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["header", "chunk"] (oneof frame)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_frame(self) -> "GetGoalContextResponse":
        _set = [f for f in ("header", "chunk") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'frame': only one field may be set, got {_set!r}")
        return self


class GoalContextEntryHeader(_ProtoModel):
    """
    GoalContextEntryHeader begins one entry in the read stream. The control plane
    rehydrates the snapshot from S3 when the blob was offloaded.
    """

    job_id: str = _Field(default="")
    goal_id: str = _Field(default="")
    created_at: ProtoTimestamp | None = _Field(default=None)
    updated_at: ProtoTimestamp | None = _Field(default=None)


class RestartRedTeamJobOptions(_ProtoModel):
    """
    RestartRedTeamJobOptions controls which attacks are included in the new job.
    """

    # Filters selecting attacks from the source job. Values use OR semantics. When empty,
    # every attack is run, including attacks that had not started before cancel.
    attack_rerun_filters: "list[AttackRerunFilter]" = _Field(
        default_factory=list,
        description="Filters selecting attacks from the source job. Values use OR semantics. When empty,\nevery attack is run, including attacks that had not started before cancel.",
    )


class AdaptiveRedTeamRoundActivityInput(_ProtoModel):
    """
    AdaptiveRedTeamRoundActivityInput identifies one outer round for one goal
    execution. goal_id is empty for the single industry-derived execution used
    by profiles without custom goals. previous_verdict is compact control state;
    attack data and adaptive memory remain outside Temporal history.
    """

    tenant_id: str = _Field(default="")
    job_id: str = _Field(default="")
    execution_id: str = _Field(default="")
    goal_id: str = _Field(default="")
    round_number: int = _Field(default=0)
    execution_epoch: ProtoUInt64 = _Field(default=0)
    previous_verdict: str = _Field(default="")
    # CP-computed per-goal customer-model in-flight budget. Zero preserves the
    # legacy default for histories created before this field existed.
    model_max_inflight: int = _Field(
        default=0,
        description="CP-computed per-goal customer-model in-flight budget. Zero preserves the\nlegacy default for histories created before this field existed.",
    )
