# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0
# DO NOT EDIT. Generated by protoc-gen-pydantic.
from __future__ import annotations
from typing import Any as _Any

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)

from ._proto_types import ProtoInt64, ProtoTimestamp, ProtoUInt64, _ProtoEnum


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class ClassificationTypes(_ProtoEnum):
    NONE_VIOLATION = ("NONE_VIOLATION", 0)
    SECURITY_VIOLATION = ("SECURITY_VIOLATION", 1)
    PRIVACY_VIOLATION = ("PRIVACY_VIOLATION", 2)
    SAFETY_VIOLATION = ("SAFETY_VIOLATION", 3)
    RELEVANCE_VIOLATION = ("RELEVANCE_VIOLATION", 4)
    CUSTOM_GUARDRAIL_PROFILE_VIOLATION = ("CUSTOM_GUARDRAIL_PROFILE_VIOLATION", 5)


class SeverityType(_ProtoEnum):
    NONE_SEVERITY = ("NONE_SEVERITY", 0)
    LOW = ("LOW", 1)
    MEDIUM = ("MEDIUM", 2)
    HIGH = ("HIGH", 3)


class AttackTechniqueTypes(_ProtoEnum):
    NONE_ATTACK_TECHNIQUE = ("NONE_ATTACK_TECHNIQUE", 0)
    DIRECT_REQUEST = ("DIRECT_REQUEST", 1)
    INDIRECT_REQUEST = ("INDIRECT_REQUEST", 2)
    INTRUCTION_INJECTION = ("INTRUCTION_INJECTION", 3)
    OBFUSCATION = ("OBFUSCATION", 4)
    FICTIONALIZATION = ("FICTIONALIZATION", 5)


class Role(_ProtoEnum):
    invalid_role = ("invalid_role", 0)
    assistant = ("assistant", 1)
    system = ("system", 2)
    user = ("user", 3)
    tool = ("tool", 4)
    # Legacy OpenAI function-calling format (deprecated by OpenAI in favor of tool role).
    # Added to support clients still sending function_call style messages.
    function = ("function", 5)


class ContentPartType(_ProtoEnum):
    """
    Supported multimodal content part types. Add new enum values as capabilities expand.
    """

    invalid_content_part_type = ("invalid_content_part_type", 0)
    text = ("text", 1)
    image_url = ("image_url", 2)
    input_audio = ("input_audio", 3)


class Action(_ProtoEnum):
    """
    Action
    """

    ActionUnspecified = ("ActionUnspecified", 0)
    Block = ("Block", 1)
    Allow = ("Allow", 2)
    Redact = ("Redact", 3)


class Application(_ProtoEnum):
    """
    Application enum definition
    """

    APPLICATION_UNSPECIFIED = ("APPLICATION_UNSPECIFIED", 0)
    APPLICATION_MICROSOFT_COPILOT = ("APPLICATION_MICROSOFT_COPILOT", 1)


class FrameDirection(_ProtoEnum):
    """
    FrameDirection enum definition
    """

    UNKNOWN = ("UNKNOWN", 0)
    SERVER_TO_CLIENT = ("SERVER_TO_CLIENT", 1)
    ClIENT_TO_SERVER = ("ClIENT_TO_SERVER", 2)


class RuleObject(_ProtoModel):
    """
    CategoryObject message definition
    """

    rule_name: str = _Field(default="")
    # The canonical name of the rule
    rule_id: int = _Field(default=0)
    # rule_id
    entity_types: list[str] = _Field(
        default_factory=list,
    )
    # The entity types
    classification: "ClassificationTypes | None" = _Field(default=None)
    # According to yaml
    profile_id: str = _Field(default="")
    # Profile id for profile-based response metadata


class HttpHdrKvObject(_ProtoModel):
    key: str = _Field(default="")
    value: str = _Field(default="")


class HttpHdrObject(_ProtoModel):
    hdr_kvs: "list[HttpHdrKvObject]" = _Field(
        default_factory=list,
    )
    # required


class Config(_ProtoModel):
    """
    Config message definition
    """

    enabled_rules: "list[RuleObject]" = _Field(
        default_factory=list,
    )
    # The list of enabled rules
    integration_tenant_id: str = _Field(default="")
    # The integration tenant id
    integration_type: str = _Field(default="")
    # The integration type


class FunctionCall(_ProtoModel):
    """
    FunctionCall represents a legacy OpenAI function invocation on an assistant message.
    Added to support the deprecated function_call format that predates tool_calls.
    Clients using the legacy format send: {"role": "assistant", "content": null, "function_call": {"name": "...", "arguments": "..."}}.
    """

    name: str = _Field(default="")
    arguments: str = _Field(default="")


class ToolFunction(_ProtoModel):
    """
    ToolFunction represents function details for tool registration or invocation.
    """

    name: str = _Field(default="")
    description: str = _Field(default="")
    parameters_json: str = _Field(default="")
    arguments_json: str = _Field(default="")


class ToolDefinition(_ProtoModel):
    """
    ToolDefinition represents a request-level tool definition.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    type_: str = _Field(
        default="",
        alias="type",
    )
    function: "ToolFunction | None" = _Field(default=None)


class ToolCall(_ProtoModel):
    """
    ToolCall represents an assistant tool invocation in a message.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    id_: str = _Field(
        default="",
        alias="id",
    )
    type_: str = _Field(
        default="",
        alias="type",
    )
    function: "ToolFunction | None" = _Field(default=None)


class ImageURL(_ProtoModel):
    """
    ImageURL carries an OpenAI-compatible image reference.
    """

    url: str = _Field(default="")


class InputAudio(_ProtoModel):
    """
    InputAudio carries inline audio content (OpenAI input_audio format).
    """

    # Base64-encoded audio data.
    data: str = _Field(
        default="",
        description="Base64-encoded audio data.",
    )
    # Audio format hint: "wav", "mp3", "flac", "ogg", "webm", "aac", "aiff", "pcm".
    # Empty or unrecognized values are handled downstream (fail-open); validation is not enforced here.
    format: str = _Field(
        default="",
        description='Audio format hint: "wav", "mp3", "flac", "ogg", "webm", "aac", "aiff", "pcm".\nEmpty or unrecognized values are handled downstream (fail-open); validation is not enforced here.',
    )


class ContentPart(_ProtoModel):
    """
    ContentPart is one element of a multimodal message content array.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    type_: "ContentPartType | None" = _Field(
        default=None,
        alias="type",
    )
    text: str = _Field(default="")
    image_url: "ImageURL | None" = _Field(default=None)
    input_audio: "InputAudio | None" = _Field(default=None)


class ContentPartList(_ProtoModel):
    """
    ContentPartList groups multimodal content parts.
    """

    items: "list[ContentPart]" = _Field(
        default_factory=list,
    )


class MessageContent(_ProtoModel):
    """
    MessageContent is either plain text or a typed multimodal part list.
    """

    text: str | None = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["text", "parts"] (oneof body)',
    )
    parts: "ContentPartList | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["text", "parts"] (oneof body)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_body(self) -> "MessageContent":
        _set = [f for f in ("text", "parts") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'body': only one field may be set, got {_set!r}")
        return self


class Message(_ProtoModel):
    """
    Message represents one chat message in the conversation.
    Role usage:
    - user/system: regular prompt/context messages.
    - assistant: model messages; assistant tool invocations go in tool_calls (current format)
    or function_call (legacy format).
    - tool: tool execution output; set tool_call_id to link to assistant tool call.
    - function: legacy function execution output (deprecated by OpenAI in favor of tool role).
    """

    role: "Role | None" = _Field(default=None)
    content: "MessageContent | None" = _Field(default=None)
    tool_calls: "list[ToolCall]" = _Field(
        default_factory=list,
    )
    tool_call_id: str = _Field(default="")
    # Legacy OpenAI function_call field on assistant messages.
    # Added to support the deprecated format where assistant invocations use
    # {"function_call": {"name": "...", "arguments": "..."}} instead of tool_calls.
    function_call: "FunctionCall | None" = _Field(
        default=None,
        description='Legacy OpenAI function_call field on assistant messages.\nAdded to support the deprecated format where assistant invocations use\n{"function_call": {"name": "...", "arguments": "..."}} instead of tool_calls.',
    )
    # Legacy function name field on function-role messages.
    # In the deprecated format, function results use {"role": "function", "name": "fn_name", "content": "..."}.
    name: str = _Field(
        default="",
        description='Legacy function name field on function-role messages.\nIn the deprecated format, function results use {"role": "function", "name": "fn_name", "content": "..."}.',
    )


class Metadata(_ProtoModel):
    user: str = _Field(default="")
    # User identity
    created_at: ProtoTimestamp | None = _Field(default=None)
    # Creation time
    src_app: str = _Field(default="")
    # Source application identity
    dst_app: str = _Field(default="")
    # Destination application identity
    sni: str = _Field(default="")
    # Server name indication
    dst_ip: str = _Field(default="")
    # Destination IP Address
    src_ip: str = _Field(default="")
    # Source IP Address
    dst_host: str = _Field(default="")
    # Destination host
    user_agent: str = _Field(default="")
    # User agent string
    client_transaction_id: str = _Field(default="")
    # Client transaction id
    model_name: str = _Field(default="")
    # Model name
    model_provider_name: str = _Field(default="")
    # Model provider name


class DetectedPII(_ProtoModel):
    """
    DetectedPII represents info related to an instance of detected PII in a message.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    message_index: ProtoUInt64 | None = _Field(default=None)
    # Index (zero-indexed) of the message in the conversation
    type_: str = _Field(
        default="",
        alias="type",
    )
    # Type of PII detected
    start_index: ProtoUInt64 | None = _Field(default=None)
    # Start character index (zero-indexed, inclusive). Relative to the content part text when content_part_index is set, otherwise relative to the full message text.
    end_index: ProtoUInt64 | None = _Field(default=None)
    # End character index (zero-indexed, exclusive). Relative to the content part text when content_part_index is set, otherwise relative to the full message text.
    content_part_index: ProtoUInt64 | None = _Field(default=None)
    # Index (zero-indexed) of the content part within the message. Present only when the request contains multipart content (multiple content blocks per message).


class DetectedSpan(_ProtoModel):
    """
    DetectedSpan represents info related to a detected span in a message.
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    message_index: ProtoUInt64 | None = _Field(default=None)
    # Index (zero-indexed) of the message in the conversation
    type_: str = _Field(
        default="",
        alias="type",
    )
    # Type of span detected
    entity_name: str = _Field(default="")
    # Name of the entity detected
    start_index: ProtoUInt64 | None = _Field(default=None)
    # Start character index (zero-indexed, inclusive). Relative to the content part text when content_part_index is set, otherwise relative to the full message text.
    end_index: ProtoUInt64 | None = _Field(default=None)
    # End character index (zero-indexed, exclusive). Relative to the content part text when content_part_index is set, otherwise relative to the full message text.
    content_part_index: ProtoUInt64 | None = _Field(default=None)
    # Index (zero-indexed) of the content part within the message. Present only when the request contains multipart content (multiple content blocks per message).


class ChatInspectRequest(_ProtoModel):
    messages: "list[Message]" = _Field(
        default_factory=list,
    )
    metadata: "Metadata | None" = _Field(default=None)
    config: "Config | None" = _Field(default=None)
    tools: "list[ToolDefinition]" = _Field(
        default_factory=list,
    )
    policy_id: str = _Field(default="")
    # Optional policy ID to select a synced custom guardrail policy for this inspection.


class DefenseClawInspectRequest(_ProtoModel):
    messages: "list[Message]" = _Field(
        default_factory=list,
    )
    metadata: "Metadata | None" = _Field(default=None)
    config: "Config | None" = _Field(default=None)
    tools: "list[ToolDefinition]" = _Field(
        default_factory=list,
    )
    dc_metadata: dict[str, _Any] | None = _Field(default=None)
    device_id: str | None = _Field(default=None)


class HttpMetaObject(_ProtoModel):
    url: str = _Field(default="")
    # required
    protocol: str = _Field(default="")


class HttpReqObject(_ProtoModel):
    method: str = _Field(default="")
    headers: "HttpHdrObject | None" = _Field(default=None)
    body: str = _Field(default="")
    # required as per yaml
    split: bool = _Field(default=False)
    last: bool = _Field(default=False)


class HttpResObject(_ProtoModel):
    status_code: int = _Field(default=0)
    # required
    status_string: str = _Field(default="")
    # required
    headers: "HttpHdrObject | None" = _Field(default=None)
    body: str = _Field(default="")
    # required
    split: bool = _Field(default=False)
    last: bool = _Field(default=False)


class HttpInspectRequest(_ProtoModel):
    http_req: "HttpReqObject | None" = _Field(default=None)
    # required as per yaml
    http_res: "HttpResObject | None" = _Field(default=None)
    http_meta: "HttpMetaObject | None" = _Field(default=None)
    metadata: "Metadata | None" = _Field(default=None)
    config: "Config | None" = _Field(default=None)
    policy_id: str = _Field(default="")
    # Optional policy ID to select a synced custom guardrail policy for this inspection.


class InspectResponse(_ProtoModel):
    """
    Definition of Response message
    """

    classifications: "list[ClassificationTypes]" = _Field(
        default_factory=list,
    )
    # According to yaml
    is_safe: bool = _Field(default=False)
    severity: "SeverityType | None" = _Field(default=None)
    rules: "list[RuleObject]" = _Field(
        default_factory=list,
    )
    attack_technique: "AttackTechniqueTypes | None" = _Field(default=None)
    explanation: str | None = _Field(default=None)
    client_transaction_id: str = _Field(default="")
    event_id: str = _Field(default="")
    processed_rules: "list[RuleObject]" = _Field(
        default_factory=list,
    )
    action: "Action | None" = _Field(default=None)
    # Configured action for the association
    detected_pii: "list[DetectedPII]" = _Field(
        default_factory=list,
    )
    detected_spans: "list[DetectedSpan]" = _Field(
        default_factory=list,
    )
    redacted_content: str | None = _Field(default=None)


class DefenseClawInspectResponse(_ProtoModel):
    classifications: "list[ClassificationTypes]" = _Field(
        default_factory=list,
    )
    # According to yaml
    is_safe: bool = _Field(default=False)
    severity: "SeverityType | None" = _Field(default=None)
    rules: "list[RuleObject]" = _Field(
        default_factory=list,
    )
    attack_technique: "AttackTechniqueTypes | None" = _Field(default=None)
    explanation: str | None = _Field(default=None)
    client_transaction_id: str = _Field(default="")
    event_id: str = _Field(default="")
    processed_rules: "list[RuleObject]" = _Field(
        default_factory=list,
    )
    action: "Action | None" = _Field(default=None)
    # Configured action for the association
    detected_pii: "list[DetectedPII]" = _Field(
        default_factory=list,
    )
    detected_spans: "list[DetectedSpan]" = _Field(
        default_factory=list,
    )
    is_redaction_enabled: bool = _Field(default=False)


class MCPMessage(_ProtoModel):
    """
    MCP JSON-RPC 2.0 Message
    Represents a pure Model Context Protocol message following JSON-RPC 2.0 specification
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # JSON-RPC version, must be "2.0"
    jsonrpc: str = _Field(
        default="",
        description='JSON-RPC version, must be "2.0"',
    )
    # Method name (present in requests and notifications)
    # Common MCP methods: tools/call, tools/list, resources/read, resources/list,
    # prompts/get, prompts/list, notifications/progress
    method: str = _Field(
        default="",
        description="Method name (present in requests and notifications)\nCommon MCP methods: tools/call, tools/list, resources/read, resources/list,\nprompts/get, prompts/list, notifications/progress",
    )
    # Method parameters (flexible JSON object)
    # Structure varies by method and can include nested objects
    params: dict[str, _Any] | None = _Field(
        default=None,
        description="Method parameters (flexible JSON object)\nStructure varies by method and can include nested objects",
    )
    # Success result (present in successful responses)
    # Structure varies by method, commonly includes content array
    result: dict[str, _Any] | None = _Field(
        default=None,
        description="Success result (present in successful responses)\nStructure varies by method, commonly includes content array",
    )
    # Error object (present in error responses)
    error: "MCPError | None" = _Field(
        default=None,
        description="Error object (present in error responses)",
    )
    # Request/response correlation ID
    # Present in requests and responses, absent in notifications
    # Can be string or number per JSON-RPC 2.0 spec
    # Using google.protobuf.Value for polymorphic JSON support
    id_: _Any | None = _Field(
        default=None,
        description="Request/response correlation ID\nPresent in requests and responses, absent in notifications\nCan be string or number per JSON-RPC 2.0 spec\nUsing google.protobuf.Value for polymorphic JSON support",
        alias="id",
    )


class MCPError(_ProtoModel):
    """
    MCP Error object for JSON-RPC 2.0 error responses
    """

    # JSON-RPC error code
    # Standard codes: -32700 (Parse error), -32600 (Invalid request),
    # -32601 (Method not found), -32602 (Invalid params), -32603 (Internal error)
    code: int = _Field(
        default=0,
        description="JSON-RPC error code\nStandard codes: -32700 (Parse error), -32600 (Invalid request),\n-32601 (Method not found), -32602 (Invalid params), -32603 (Internal error)",
    )
    # Human-readable error message
    message: str = _Field(
        default="",
        description="Human-readable error message",
    )
    # Optional additional error data
    data: dict[str, _Any] | None = _Field(
        default=None,
        description="Optional additional error data",
    )


class MCPInspectResponse(_ProtoModel):
    """
    MCP Inspect Response wrapping inspection results in JSON-RPC 2.0 format
    """

    model_config = _ConfigDict(populate_by_name=True, protected_namespaces=())

    # JSON-RPC version, always "2.0"
    jsonrpc: str = _Field(
        default="",
        description='JSON-RPC version, always "2.0"',
    )
    # Success result containing inspection details
    result: "InspectResponse | None" = _Field(
        default=None,
        description='Success result containing inspection details\nOnly one of the fields can be specified with: ["result", "error"] (oneof response)',
    )
    # Error result for failed inspections
    error: "MCPInspectError | None" = _Field(
        default=None,
        description='Error result for failed inspections\nOnly one of the fields can be specified with: ["result", "error"] (oneof response)',
    )
    # Request ID echoed from the inspected MCP message
    # Null if the inspected message was a notification
    # Using google.protobuf.Value for polymorphic JSON support
    id_: _Any | None = _Field(
        default=None,
        description="Request ID echoed from the inspected MCP message\nNull if the inspected message was a notification\nUsing google.protobuf.Value for polymorphic JSON support",
        alias="id",
    )

    @_model_validator(mode="after")
    def _validate_oneof_response(self) -> "MCPInspectResponse":
        _set = [f for f in ("result", "error") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'response': only one field may be set, got {_set!r}"
            )
        return self


class MCPInspectError(_ProtoModel):
    """
    Error response for MCP inspection failures
    """

    # JSON-RPC error code
    # Standard: -32700 (Parse error), -32600 (Invalid Request), -32601 (Method not found)
    # -32602 (Invalid params), -32603 (Internal error)
    # Custom:  -32000 (Service unavailable), -32001 (Unauthorized),
    # -32002 (Forbidden), -32003 (Rate limited)
    code: int = _Field(
        default=0,
        description="JSON-RPC error code\nStandard: -32700 (Parse error), -32600 (Invalid Request), -32601 (Method not found)\n-32602 (Invalid params), -32603 (Internal error)\nCustom:  -32000 (Service unavailable), -32001 (Unauthorized),\n-32002 (Forbidden), -32003 (Rate limited)",
    )
    # Human-readable error message
    message: str = _Field(
        default="",
        description="Human-readable error message",
    )
    # Optional additional error context
    data: dict[str, _Any] | None = _Field(
        default=None,
        description="Optional additional error context",
    )


class ApplicationInfo(_ProtoModel):
    """
    ApplicationInfo message definition
    """

    application: "Application | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["application", "casp_application_name"] (oneof application_choice)',
    )
    # secure access will have casp_application_name
    casp_application_name: str | None = _Field(
        default=None,
        description='secure access will have casp_application_name\nOnly one of the fields can be specified with: ["application", "casp_application_name"] (oneof application_choice)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_application_choice(self) -> "ApplicationInfo":
        _set = [
            f
            for f in ("application", "casp_application_name")
            if getattr(self, f) is not None
        ]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'application_choice': only one field may be set, got {_set!r}"
            )
        return self


class WebSocketMetadata(_ProtoModel):
    """
    WebSocketMetadata message definition
    """

    client_transaction_id: str = _Field(default="")
    # Client transaction id
    application: "ApplicationInfo | None" = _Field(default=None)
    url: str = _Field(default="")
    req_headers: "HttpHdrObject | None" = _Field(default=None)
    resp_headers: "HttpHdrObject | None" = _Field(default=None)


class WebSocketFrame(_ProtoModel):
    """
    WebSocketFrame message definition
    """

    direction: "FrameDirection | None" = _Field(default=None)
    body: bytes = _Field(default=b"")
    frame_id: ProtoInt64 = _Field(default=0)
    op_code: int = _Field(default=0)


class WebSocketInspectRequest(_ProtoModel):
    """
    WebSocketInspectRequest message definition
    """

    frames: "list[WebSocketFrame]" = _Field(
        default_factory=list,
    )
    config: "Config | None" = _Field(default=None)
    metadata: "WebSocketMetadata | None" = _Field(default=None)


class WebSocketInspectResponse(_ProtoModel):
    """
    WebSocketInspectResponse message definition
    """

    inspect_response: "InspectResponse | None" = _Field(default=None)
    frame_id: ProtoInt64 = _Field(default=0)
    direction: "FrameDirection | None" = _Field(default=None)
    # It will include violated content in frame upto 100 words only.
    violated_content: str = _Field(
        default="",
        description="It will include violated content in frame upto 100 words only.",
    )
    decoded_content: str = _Field(default="")
