# Copyright 2026 Cisco Systems, Inc. and its affiliates
# SPDX-License-Identifier: Apache-2.0
# DO NOT EDIT. Generated by protoc-gen-pydantic.
from __future__ import annotations

from pydantic import (
    BaseModel as _BaseModel,
    ConfigDict as _ConfigDict,
    Field as _Field,
    model_validator as _model_validator,
)

from ._proto_types import ProtoUInt64, _ProtoEnum

from aidefense.pydantic.runtime.ai_defense.inspection.v1.inspection_pydantic import Message

from aidefense.pydantic.runtime.ai_defense.inspection.v1.inspection_pydantic import Config

from aidefense.pydantic.runtime.ai_defense.inspection.v1.inspection_pydantic import InspectResponse


class _ProtoModel(_BaseModel):
    """Base class for generated Pydantic models with ProtoJSON helpers."""

    model_config = _ConfigDict(
        use_enum_values=True,
        ser_json_bytes="base64",
        val_json_bytes="base64",
        ser_json_inf_nan="strings",
    )

    def model_dump(self, **kwargs) -> dict:
        """Serialize to a dict using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump(**kwargs)

    def model_dump_json(self, **kwargs) -> str:
        """Serialize to a JSON string using ProtoJSON conventions.

        Omits fields with default (zero) values and uses original proto
        field names (aliases for reserved-name fields, proto names otherwise).
        Override kwargs to change defaults.
        """
        kwargs.setdefault("exclude_defaults", True)
        kwargs.setdefault("by_alias", True)
        return super().model_dump_json(**kwargs)


class Direction(_ProtoEnum):
    """
    Direction identifies whether an event contains data sent to or received from
    an LLM. DIRECTION_REQUEST carries prompt/context and tool-result content;
    DIRECTION_RESPONSE carries model output and assistant tool calls. Sequences
    are ordered across both directions within one stream.
    """

    DIRECTION_UNSPECIFIED = ("DIRECTION_UNSPECIFIED", 0)
    DIRECTION_REQUEST = ("DIRECTION_REQUEST", 1)
    DIRECTION_RESPONSE = ("DIRECTION_RESPONSE", 2)


class InspectionContext(_ProtoModel):
    """
    InspectionContext carries correlation data. Tenant and connection identity
    must come from authenticated gRPC metadata rather than client payload fields.
    """

    # State associated with this context is maintained only for the lifetime of
    # the InspectEventStream RPC. It is not persisted or shared across separate
    # API calls, even when they use the same conversation_id.
    # session_id correlates inspection data across API calls in one session.
    session_id: str = _Field(
        default="",
        description="State associated with this context is maintained only for the lifetime of\nthe InspectEventStream RPC. It is not persisted or shared across separate\nAPI calls, even when they use the same conversation_id.\nsession_id correlates inspection data across API calls in one session.",
    )
    # request_id uniquely correlates the originating client request.
    request_id: str = _Field(
        default="",
        description="request_id uniquely correlates the originating client request.",
    )
    # conversation_id identifies the logical LLM conversation for correlation;
    # it does not resume or share server-side state across API calls.
    conversation_id: str = _Field(
        default="",
        description="conversation_id identifies the logical LLM conversation for correlation;\nit does not resume or share server-side state across API calls.",
    )
    # actor_id identifies the application actor without carrying tenant identity.
    actor_id: str = _Field(
        default="",
        description="actor_id identifies the application actor without carrying tenant identity.",
    )


class ConversationPayload(_ProtoModel):
    """
    ConversationPayload uses the canonical ChatInspect message representation.
    Complete messages must be sent;
    """

    # messages contains one or more complete ChatInspect conversation messages.
    messages: "list[Message]" = _Field(
        default_factory=list,
        description="messages contains one or more complete ChatInspect conversation messages.",
    )


class InspectionEvent(_ProtoModel):
    """
    InspectionEvent contains transport-neutral semantic content. source offsets
    let the service map findings for client-generated overlap back to canonical
    content. When either offset is present, both must be present and end must be
    greater than or equal to start; the service enforces this cross-field rule.
    """

    # message_id identifies the logical message represented by this event.
    # Fragments for one message may be spread across multiple sequences, and
    # one RPC may carry multiple message IDs. The server emits one event per
    # (message_id, direction) pair within the RPC. Server-side conversation
    # state is scoped to this RPC; message_id does not resume state across API
    # calls.
    message_id: str = _Field(
        default="",
        description="message_id identifies the logical message represented by this event.\nFragments for one message may be spread across multiple sequences, and\none RPC may carry multiple message IDs. The server emits one event per\n(message_id, direction) pair within the RPC. Server-side conversation\nstate is scoped to this RPC; message_id does not resume state across API\ncalls.",
    )
    # sequence is globally increasing across request and response events.
    sequence: ProtoUInt64 = _Field(
        default=0,
        description="sequence is globally increasing across request and response events.",
    )
    # source identifies the framework, endpoint, or event source for debugging.
    source: str = _Field(
        default="",
        description="source identifies the framework, endpoint, or event source for debugging.",
    )
    # direction identifies whether the content is an LLM request or response.
    direction: "Direction | None" = _Field(
        default=None,
        description="direction identifies whether the content is an LLM request or response.",
    )
    # is_final marks the final event for this InspectEventStream RPC and closes
    # event ingestion after this event is accepted.
    is_final: bool = _Field(
        default=False,
        description="is_final marks the final event for this InspectEventStream RPC and closes\nevent ingestion after this event is accepted.",
    )
    conversation: "ConversationPayload | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["conversation"] (oneof payload)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_payload(self) -> "InspectionEvent":
        _set = [f for f in ("conversation",) if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(
                f"oneof 'payload': only one field may be set, got {_set!r}"
            )
        return self


class InspectStreamStart(_ProtoModel):
    """
    InspectStreamStart must be the first and only start frame on a stream.
    Inspection config is a fallback only: the server must reject it when the
    authenticated connection already selects a policy.
    """

    # context carries required correlation data for the stream.
    context: "InspectionContext | None" = _Field(
        default=None,
        description="context carries required correlation data for the stream.",
    )
    # inspection_config reuses the canonical inspection API configuration.
    inspection_config: "Config | None" = _Field(
        default=None,
        description="inspection_config reuses the canonical inspection API configuration.",
    )


class InspectStreamEvents(_ProtoModel):
    """
    InspectStreamEvents groups one or more ordered inspection events in a frame.
    """

    # events must preserve their global sequence order.
    events: "list[InspectionEvent]" = _Field(
        default_factory=list,
        description="events must preserve their global sequence order.",
    )


class InspectStreamRequest(_ProtoModel):
    """
    InspectStreamRequest carries exactly one start frame followed by one or more
    event frames. The client half-closes its send side to flush the final window.
    """

    start: "InspectStreamStart | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["start", "events"] (oneof frame)',
    )
    events: "InspectStreamEvents | None" = _Field(
        default=None,
        description='Only one of the fields can be specified with: ["start", "events"] (oneof frame)',
    )

    @_model_validator(mode="after")
    def _validate_oneof_frame(self) -> "InspectStreamRequest":
        _set = [f for f in ("start", "events") if getattr(self, f) is not None]
        if len(_set) > 1:
            raise ValueError(f"oneof 'frame': only one field may be set, got {_set!r}")
        return self


class InspectionResult(_ProtoModel):
    """
    InspectionResult acknowledges the inspected event windows identified by
    through_sequences and returns the canonical inspection decision. It
    intentionally contains no content or released_events; clients decide whether
    to release or block their locally buffered content from inspect_response.
    """

    # Each through_sequences entry acknowledges inspection through that event
    # sequence. The list must not contain duplicate sequence IDs.
    through_sequences: list[ProtoUInt64] = _Field(
        default_factory=list,
        description="Each through_sequences entry acknowledges inspection through that event\nsequence. The list must not contain duplicate sequence IDs.",
    )
    # inspect_response is the canonical AI Defense inspection result.
    inspect_response: "InspectResponse | None" = _Field(
        default=None,
        description="inspect_response is the canonical AI Defense inspection result.",
    )
